# accept
# Autogenerated from man page /usr/share/man/man8/accept.8.gz
# using Deroffing man parser
complete -c accept -s E --description 'br Forces encryption when connecting to the server.'
complete -c accept -s U --description 'br Sets the username that is sent when connecti… [See Man Page]'
complete -c accept -s h --description 'br Chooses an alternate server.'
complete -c accept -s r --description '.'

