# amavisd
# Autogenerated from man page /usr/share/man/man8/amavisd.8
# using Darwin man parser
complete -c amavisd -s u --description 'Run using this user id.'
complete -c amavisd -s g --description 'Run using this group id.'
complete -c amavisd -s c --description 'Use the specified configuration file instead of… [See Man Page]'
complete -c amavisd -s i --description '.'
complete -c amavisd -s m --description 'Maximum number of pre-forked children.'
complete -c amavisd -s p --description 'Listen on specified local TCP port(s) instead o… [See Man Page]'
complete -c amavisd -s L --description 'Use the specified lock file instead of the defa… [See Man Page]'
complete -c amavisd -s P --description 'Use the specified PID file instead of the defau… [See Man Page]'
complete -c amavisd -s H --description 'Use the specified home directory instead of the… [See Man Page]'
complete -c amavisd -s D --description 'Use the specified directory for for bdb, nanny,… [See Man Page]'
complete -c amavisd -s Q --description 'Use the specified quarantine directory instead … [See Man Page]'
complete -c amavisd -s R --description 'Use the specified chroot directory instead of t… [See Man Page]'
complete -c amavisd -s S --description 'Use the specified chroot directory instead of t… [See Man Page]'
complete -c amavisd -s T --description 'Use the specified temporary directory instead o… [See Man Page]'

