# argv0
# Autogenerated from man page /usr/local/share/man/man1/argv0.1
# using Deroffing man parser
complete -c argv0 -o bin/csh --description 'csh will think it is a login shell and behave accordingly.'

