# bzr
# Autogenerated from man page /usr/local/share/man/man1/bzr.1
# using Deroffing man parser
complete -c bzr -l dry-run --description 'add them.'
complete -c bzr -l file-ids-from --description 'It looks up ids trying to find a matching paren… [See Man Page]'
complete -c bzr -l new --description 'the first argument, if any, or the current tree… [See Man Page]'
complete -c bzr -l no-remember --description 'to use the default.   To change the default, use --remember.'
complete -c bzr -l force -l force --description 'will be merged with the current working tree, i… [See Man Page]'
complete -c bzr -s r -s r -s r --description 'also valid.'
complete -c bzr -l verbose --description '.'
complete -c bzr -o Olog_format --description '.'
complete -c bzr -l 'remember.' --description '.'

