# callgrind_annotate
# Autogenerated from man page /usr/local/share/man/man1/callgrind_annotate.1
# using Deroffing man parser
complete -c callgrind_annotate -s h -l help --description 'Show summary of options.'
complete -c callgrind_annotate -l version --description 'Show version of callgrind_annotate.'
complete -c callgrind_annotate -l show --description 'Only show figures for events A,B,C.'
complete -c callgrind_annotate -l sort --description 'Sort columns by events A,B,C [event column order].'
complete -c callgrind_annotate -l threshold --description 'Percentage of counts (of primary sort event) we… [See Man Page]'
complete -c callgrind_annotate -l auto --description 'Annotate all source files containing functions … [See Man Page]'
complete -c callgrind_annotate -l context --description 'Print N lines of context before and after annotated lines.'
complete -c callgrind_annotate -l inclusive --description 'Add subroutine costs to functions calls.'
complete -c callgrind_annotate -l tree --description 'Print for each function their callers, the call… [See Man Page]'
complete -c callgrind_annotate -s I -l include --description 'Add dir to the list of directories to search for source files.'

