# callgrind_control
# Autogenerated from man page /usr/local/share/man/man1/callgrind_control.1
# using Deroffing man parser
complete -c callgrind_control -s h -l help --description 'Show a short description, usage, and summary of options.'
complete -c callgrind_control -l version --description 'Show version of callgrind_control.'
complete -c callgrind_control -s l -l long --description 'Show also the working directory, in addition to… [See Man Page]'
complete -c callgrind_control -s s -l stat --description 'Show statistics information about active Callgrind runs.'
complete -c callgrind_control -s b -l back --description 'Show stack/back traces of each thread in active Callgrind runs.'
complete -c callgrind_control -s e --description 'Show the current per-thread, exclusive cost val… [See Man Page]'
complete -c callgrind_control -l 'dump[' --description 'Request the dumping of profile information.'
complete -c callgrind_control -s z -l zero --description 'Zero all event counters.'
complete -c callgrind_control -s k -l kill --description 'Force a Callgrind run to be terminated.'
complete -c callgrind_control -l instr --description 'Switch instrumentation mode on or off.'
complete -c callgrind_control -s w --description 'Specify the startup directory of an active Callgrind run.'
complete -c callgrind_control -l 'instr-atstart.' --description '.'

