# certadmin
# Autogenerated from man page /usr/share/man/man8/certadmin.8
# using Darwin man parser
complete -c certadmin -l get-private-key-passphrase --description 'Retrieve the passphrase from the keychain for t… [See Man Page]'
complete -c certadmin -l default-certificate-path --description 'Retrieve the full path for the default certificate.'
complete -c certadmin -l default-certificate-authority-chain-path --description 'Retrieve the full path for the default certific… [See Man Page]'
complete -c certadmin -l default-private-key-path --description 'Retrieve the full path for the default private key.'
complete -c certadmin -l default-concatenation-path --description 'Retrieve the full path for the default certific… [See Man Page]'

