# chpst
# Autogenerated from man page /usr/local/share/man/man8/chpst.8
# using Deroffing man parser
complete -c chpst -s u --description 'setuidgid.'
complete -c chpst -s U --description 'envuidgid.'
complete -c chpst -s b --description 'argv0.  Run  prog with  argv0 as the 0th argument.'
complete -c chpst -s e --description 'envdir.'
complete -c chpst -s / --description 'chroot.'
complete -c chpst -s n --description 'nice.  Add  inc to the  nice (2) value before starting R prog .'
complete -c chpst -s l --description 'lock.'
complete -c chpst -s L --description 'The same as -l, but fail immediately if  lock i… [See Man Page]'
complete -c chpst -s m --description 'limit memory.'
complete -c chpst -s d --description 'limit data segment.'
complete -c chpst -s o --description 'limit open files.'
complete -c chpst -s p --description 'limit processes.'
complete -c chpst -s f --description 'limit output size.  Limit the output file size to  bytes bytes.'
complete -c chpst -s c --description 'limit core size.  Limit the core file size to  bytes bytes.'
complete -c chpst -s v --description 'verbose.  Print verbose messages to standard error.'
complete -c chpst -s P --description 'pgrphack.  Run  prog in a new process group.'
complete -c chpst -s 0 --description 'Close standard input before starting R prog .'
complete -c chpst -s 1 --description 'Close standard output before starting R prog .'
complete -c chpst -s 2 --description 'Close standard error before starting prog .'

