# ct_run
# Autogenerated from man page /usr/local/share/man/man1/ct_run.1
# using Deroffing man parser
complete -c ct_run -o erl_args --description 'it\'s possible to divide the options on the ct_r… [See Man Page]'
complete -c ct_run -o help --description 'it prints all valid start flags to stdout.'

