# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1
# using Darwin man parser
complete -c ctags -s d --description 'create tags for #defines that don\'t take argume… [See Man Page]'
complete -c ctags -s t --description 'create tags for typedefs, structs, unions, and enums.'
complete -c ctags -s v --description 'An index of the form expected by vgrind 1 is pr… [See Man Page]'

