# cvsbug
# Autogenerated from man page /usr/share/man/man8/cvsbug.8
# using Deroffing man parser
complete -c cvsbug -s f --description 'specify a file (problem-report) which already c… [See Man Page]'
complete -c cvsbug -s t --description 'Change mail address at the support site for problem reports.'
complete -c cvsbug -s P --description 'print the form specified by the environment var… [See Man Page]'
complete -c cvsbug -s L --description 'print the list of available categories.   No mail is sent.'
complete -c cvsbug -l request-id --description 'sends mail to the default support site, or  sit… [See Man Page]'
complete -c cvsbug -s v --description 'Display the  cvsbug version number.'

