# diameter_compile
# Autogenerated from man page /usr/local/share/man/man1/diameter_compile.1
# using Deroffing man parser
complete -c diameter_compile -s o --description 'Write generated source to the specified directory.'
complete -c diameter_compile -o E: --description '.'
complete -c diameter_compile -o H: --description 'Supress erl and hrl generation, respectively.'
complete -c diameter_compile -l name --description '.'
complete -c diameter_compile -l prefix --description 'Set @name or @prefix to the specified string.'
complete -c diameter_compile -l inherits --description 'Append @inherits of the specified module.'

