# dnssec-revoke
# Autogenerated from man page /usr/share/man/man8/dnssec-revoke.8.gz
# using Deroffing man parser
complete -c dnssec-revoke -s h --description 'Emit usage message and exit.'
complete -c dnssec-revoke -s K --description 'Sets the directory in which the key files are to reside.'
complete -c dnssec-revoke -s r --description 'After writing the new keyset files remove the o… [See Man Page]'
complete -c dnssec-revoke -s v --description 'Sets the debugging level.'
complete -c dnssec-revoke -s E --description 'Use the given OpenSSL engine.'
complete -c dnssec-revoke -s f --description 'Force overwrite: Causes dnssec-revoke to write … [See Man Page]'
complete -c dnssec-revoke -s R --description 'Print the key tag of the key with the REVOKE bi… [See Man Page]'

