# dnssec-dsfromkey
# Autogenerated from man page /usr/share/man/man8/dnssec-dsfromkey.8.gz
# using Deroffing man parser
complete -c dnssec-dsfromkey -s 1 --description 'Use SHA-1 as the digest algorithm (the default … [See Man Page]'
complete -c dnssec-dsfromkey -s 2 --description 'Use SHA-256 as the digest algorithm.'
complete -c dnssec-dsfromkey -s a --description 'Select the digest algorithm.'
complete -c dnssec-dsfromkey -s K --description 'Look for key files (or, in keyset mode, keyset-… [See Man Page]'
complete -c dnssec-dsfromkey -s f --description 'Zone file mode: in place of the keyfile name, t… [See Man Page]'
complete -c dnssec-dsfromkey -s A --description 'Include ZSK\'s when generating DS records.'
complete -c dnssec-dsfromkey -s l --description 'Generate a DLV set instead of a DS set.'
complete -c dnssec-dsfromkey -s s --description 'Keyset mode: in place of the keyfile name, the … [See Man Page]'
complete -c dnssec-dsfromkey -s c --description 'Specifies the DNS class (default is IN).'
complete -c dnssec-dsfromkey -s v --description 'Sets the debugging level.'

