# dnssec-settime
# Autogenerated from man page /usr/share/man/man8/dnssec-settime.8.gz
# using Deroffing man parser
complete -c dnssec-settime -s f --description 'Force an update of an old-format key with no metadata fields.'
complete -c dnssec-settime -s K --description 'Sets the directory in which the key files are to reside.'
complete -c dnssec-settime -s h --description 'Emit usage message and exit.'
complete -c dnssec-settime -s v --description 'Sets the debugging level.'
complete -c dnssec-settime -s E --description 'Use the given OpenSSL engine.'
complete -c dnssec-settime -s P --description '.'
complete -c dnssec-settime -s A --description '.'
complete -c dnssec-settime -s R --description '.'
complete -c dnssec-settime -s I --description '.'
complete -c dnssec-settime -s D --description 'options.'
complete -c dnssec-settime -s S --description '.'
complete -c dnssec-settime -s i --description '.'
complete -c dnssec-settime -s u --description '.'
complete -c dnssec-settime -s p --description '.'

