# dsh
# Autogenerated from man page /usr/local/share/man/man1/dsh.1
# using Deroffing man parser
complete -c dsh -l verbose -s v --description 'Give verbose output of the execution process. PP.'
complete -c dsh -l quiet -s q --description 'Makes output quieter. PP.'
complete -c dsh -l machine -s m --description 'Adds   machinename  to the list of machines tha… [See Man Page]'
complete -c dsh -l all -s a --description 'Add all machines found in   /etc/dsh/machines.'
complete -c dsh -l group -s g --description 'Add all machines found in   /etc/dsh/group/ gro… [See Man Page]'
complete -c dsh -l file -s f --description 'Add all machines found in the specified file to… [See Man Page]'
complete -c dsh -l remoteshell -s r --description 'Execute remote shell   shellname as the remote shell.'
complete -c dsh -l remoteshellopt -s o --description 'Add one option   rshoption to the list of optio… [See Man Page]'
complete -c dsh -l help -s h --description 'Output help message and exits.'
complete -c dsh -l wait-shell -s w --description 'Executes on each machine and waits for the exec… [See Man Page]'
complete -c dsh -l concurrent-shell -s c --description 'Executes shell concurrently.'
complete -c dsh -l show-machine-names -s M --description 'Prepends machine names on the standard output.'
complete -c dsh -l hide-machine-names -s H --description 'Do not prepend machine names on the standard output.'
complete -c dsh -l duplicate-input -s i --description 'Duplicates the input to dsh process to individu… [See Man Page]'
complete -c dsh -l bufsize -s b --description 'Sets the buffer size used in replicating input … [See Man Page]'
complete -c dsh -l version -s V --description 'Outputs version information and exits.'
complete -c dsh -l num-topology -s N --description 'Changes the current topology from 1.'
complete -c dsh -l forklimit -s F --description 'Similar to .'

