# dshbak
# Autogenerated from man page /usr/local/share/man/man1/dshbak.1
# using Deroffing man parser
complete -c dshbak -s h --description 'Display a summary of command line options.'
complete -c dshbak -s c --description 'Do not display identical output from nodes twice.'
complete -c dshbak -s d --description 'Write consolidated node output to separate file… [See Man Page]'
complete -c dshbak -s f --description 'With -d, force creation of specified DIR.'

