# dvipdf
# Autogenerated from man page /usr/local/share/man/man1/dvipdf.1
# using Deroffing man parser
complete -c dvipdf -s q --description 'option, and pipes its output into gs (1) with t… [See Man Page]'
complete -c dvipdf -o dNOPAUSE -o dBATCH -o sDEVICE --description '.'
complete -c dvipdf -o sOutputFile --description 'and any options from the command-line.'

