# dvtm
# Autogenerated from man page /usr/local/share/man/man1/dvtm.1
# using Deroffing man parser
complete -c dvtm -s v --description 'prints version information to standard output, then exits.'
complete -c dvtm -s m --description 'set default modifier at runtime.'
complete -c dvtm -s d --description 'set the delay ncurses waits before deciding if … [See Man Page]'
complete -c dvtm -s h --description 'set the scrollback history buffer size at runtime.'
complete -c dvtm -s s --description 'if status-fifo is a named pipe, its content is … [See Man Page]'

