# dynamic_pager
# Autogenerated from man page /usr/share/man/man8/dynamic_pager.8.gz
# using Darwin man parser
complete -c dynamic_pager -s F --description 'The base name of the filename to use for the ex… [See Man Page]'
complete -c dynamic_pager -s H --description 'If there are less than high-water-trigger bytes… [See Man Page]'
complete -c dynamic_pager -s L --description 'If there are more than low-water-trigger bytes … [See Man Page]'
complete -c dynamic_pager -s P --description 'This option is currently unimplemented.  ==========.'
complete -c dynamic_pager -s S --description 'The fixed filesize [in bytes] to use for the paging files.'

