# erl_call
# Autogenerated from man page /usr/local/share/man/man1/erl_call.1
# using Deroffing man parser
complete -c erl_call -s a --description '(optional): Applies the specified function and … [See Man Page]'
complete -c erl_call -s c --description '(optional): Use this option to specify a certain cookie.'
complete -c erl_call -o d: --description '(optional): Debug mode.'
complete -c erl_call -o e: --description '(optional): Reads a sequence of Erlang expressi… [See Man Page]'
complete -c erl_call -s h --description '(optional): Specifies the name of the hidden no… [See Man Page]'
complete -c erl_call -o m: --description '(optional): Reads an Erlang module from stdin and compiles it.'
complete -c erl_call -s n --description '(one of -n, -name, -sname is required): Has the… [See Man Page]'
complete -c erl_call -o name --description '(one of -n, -name, -sname is required): Node is… [See Man Page]'
complete -c erl_call -o q: --description '(optional): Halts the Erlang node specified with the -n switch.'
complete -c erl_call -o r: --description '(optional): Generates a random name of the hidd… [See Man Page]'
complete -c erl_call -o s: --description '(optional): Starts a distributed Erlang node if necessary.'
complete -c erl_call -o sname --description '(one of -n, -name, -sname is required): Node is… [See Man Page]'
complete -c erl_call -o v: --description '(optional): Prints a lot of verbose information.'
complete -c erl_call -s x --description '(optional): Specifies another name of the Erlan… [See Man Page]'
complete -c erl_call -o 'module(lolita).' --description '.'
complete -c erl_call -o 'compile(export_all).' --description 'start() ->         P = processes(),         F =… [See Man Page]'

