# erlc
# Autogenerated from man page /usr/local/share/man/man1/erlc.1
# using Deroffing man parser
complete -c erlc -s I --description 'Instructs the compiler to search for include fi… [See Man Page]'
complete -c erlc -s o --description 'The directory where the compiler should place the output files.'
complete -c erlc -o Dname: --description 'Defines a macro.'
complete -c erlc -o Dname --description 'Defines a macro with the given value.'
complete -c erlc -o Werror: --description 'Makes all warnings into errors.'
complete -c erlc -o Wnumber: --description 'Sets warning level to number.  Default is 1.'
complete -c erlc -o W: --description 'Same as -W1.  Default.'
complete -c erlc -o v: --description 'Enables verbose output.'
complete -c erlc -s b --description 'Specifies the type of output file.'
complete -c erlc -o smp: --description 'Compile using the SMP emulator.'
complete -c erlc -o M: --description 'Produces a Makefile rule to track headers dependencies.'
complete -c erlc -o MF --description 'Like the -M option above, except that the Makef… [See Man Page]'
complete -c erlc -o MD: --description 'Same as -M -MF <File>. Pbeam.'
complete -c erlc -o MT --description 'In conjunction with -M or -MF, change the name … [See Man Page]'
complete -c erlc -o MQ --description 'Like the -MT option above, except that characte… [See Man Page]'
complete -c erlc -o MP: --description 'In conjunction with -M or -MF, add a phony targ… [See Man Page]'
complete -c erlc -o MG: --description 'In conjunction with -M or -MF, consider missing… [See Man Page]'
complete -c erlc -l : --description 'Signals that no more options will follow.'
complete -c erlc -o pa --description 'Appends directory to the front of the code path… [See Man Page]'
complete -c erlc -o pz --description 'Appends directory to the code path in the invok… [See Man Page]'

