# erlsrv
# Autogenerated from man page /usr/local/share/man/man1/erlsrv.1
# using Deroffing man parser
complete -c erlsrv -o 'st[opaction]' --description 'Defines the StopAction, the command given to th… [See Man Page]'
complete -c erlsrv -o 'on[fail]' --description 'Specifies the action to take when the Erlang em… [See Man Page]'
complete -c erlsrv -o 'm[achine]' --description 'The complete path to the Erlang emulator, never… [See Man Page]'
complete -c erlsrv -o 'e[nv]' --description 'Edits the environment block for the service.'
complete -c erlsrv -o 'w[orkdir]' --description 'The initial working directory of the Erlang emulator.'
complete -c erlsrv -o 'p[riority]' --description 'The priority of the Erlang emulator.'
complete -c erlsrv -o 'd[ebugtype]' --description 'Specifies where shell output should be sent, de… [See Man Page]'
complete -c erlsrv -o 'ar[gs]' --description 'Additional arguments to the Erlang emulator, av… [See Man Page]'
complete -c erlsrv -o 'i[nternalservicename]' --description 'Only allowed for add.'
complete -c erlsrv -o 'c[omment]' --description 'Specifies a textual comment describing the service.'

