# escript
# Autogenerated from man page /usr/local/share/man/man1/escript.1
# using Deroffing man parser
complete -c escript -o 'include_lib(' --description 'to include the record definitions for the recor… [See Man Page]'
complete -c escript -o 'mode(compile).' --description 'Execution of interpreted code is slower than compiled code.'
complete -c escript -o c: --description 'Compile the escript regardless of the value of … [See Man Page]'
complete -c escript -o d: --description 'Debug the escript.'
complete -c escript -o i: --description 'Interpret the escript regardless of the value o… [See Man Page]'
complete -c escript -o s: --description 'Only perform a syntactic and semantic check of the script file.'
complete -c escript -o n: --description 'Compile the escript using the +native flag.'

