# fftw-wisdom
# Autogenerated from man page /usr/local/share/man/man1/fftw-wisdom.1
# using Deroffing man parser
complete -c fftw-wisdom -s h -l help --description 'Display help on the command-line options and usage.'
complete -c fftw-wisdom -s V -l version --description 'Print the version number and copyright information.'
complete -c fftw-wisdom -s v -l verbose --description 'Verbose output.'
complete -c fftw-wisdom -s c -l canonical --description 'Optimize/pre-plan a canonical set of sizes: all… [See Man Page]'
complete -c fftw-wisdom -s t -l time-limit --description 'Stop after a time of  hours (hours) has elapsed… [See Man Page]'
complete -c fftw-wisdom -s o -l output-file --description 'Send wisdom output to  file rather than to stan… [See Man Page]'
complete -c fftw-wisdom -s m -l 'measure;' -s e -l 'estimate;' -s x -l exhaustive --description 'Normally,   fftw-wisdom creates plans in FFTW_P… [See Man Page]'
complete -c fftw-wisdom -s n -l no-system-wisdom --description 'Do not import the system wisdom from  /etc/fftw… [See Man Page]'
complete -c fftw-wisdom -s w --description 'option).'
complete -c fftw-wisdom -l wisdom-file --description 'Import wisdom from file (in addition to the sys… [See Man Page]'

