# fslsfonts
# Autogenerated from man page /usr/X11/share/man/man1/fslsfonts.1.gz
# using Deroffing man parser
complete -c fslsfonts -s u --description 'This option indicates that the output should be left unsorted.'

