# gdk-pixbuf-csource
# Autogenerated from man page /usr/local/share/man/man1/gdk-pixbuf-csource.1
# using Deroffing man parser
complete -c gdk-pixbuf-csource -l build-list --description 'option, a list of (name, image) pairs to genera… [See Man Page]'
complete -c gdk-pixbuf-csource -l stream --description '.'
complete -c gdk-pixbuf-csource -l struct --description '.'
complete -c gdk-pixbuf-csource -l macros --description '.'
complete -c gdk-pixbuf-csource -l rle --description '.'
complete -c gdk-pixbuf-csource -l raw --description '.'
complete -c gdk-pixbuf-csource -l extern --description '.'
complete -c gdk-pixbuf-csource -l static --description '.'
complete -c gdk-pixbuf-csource -l decoder --description '.'
complete -c gdk-pixbuf-csource -l name --description '.'
complete -c gdk-pixbuf-csource -s h -l help --description '.'
complete -c gdk-pixbuf-csource -s v -l version --description '.'
complete -c gdk-pixbuf-csource -l g-fatal-warnings --description '.'

