# geoipupdate
# Autogenerated from man page /usr/local/share/man/man1/geoipupdate.1
# using Deroffing man parser
complete -c geoipupdate -s v --description 'Verbose mode, prints out the steps that geoipupdate takes.'
complete -c geoipupdate -s d --description 'Specify a custom directory target to install th… [See Man Page]'
complete -c geoipupdate -s f --description 'Specifies the configuration file that contains the license key.'

