# geoiplookup
# Autogenerated from man page /usr/local/share/man/man1/geoiplookup.1
# using Deroffing man parser
complete -c geoiplookup -s f --description 'Specify a custom path to a single GeoIP datafile.'
complete -c geoiplookup -s d --description 'Specify a custom directory containing GeoIP datafile(s).'
complete -c geoiplookup -s v --description 'Lists the date and build number for the GeoIP datafile(s).'

