# geoiplookup6
# Autogenerated from man page /usr/local/share/man/man1/geoiplookup6.1
# using Deroffing man parser
complete -c geoiplookup6 -s f --description 'Specify a custom path to a single GeoIP datafile.'
complete -c geoiplookup6 -s d --description 'Specify a custom directory containing GeoIP datafile(s).'
complete -c geoiplookup6 -s v --description 'Lists the date and build number for the GeoIP datafile(s).'

