# gist
# Autogenerated from man page /usr/local/share/man/man1/gist.1
# using Type1
complete -c gist -s p -l private --description 'Create a private gist instead of a public gist.'
complete -c gist -s t -l type --description 'Set the file extension explicitly.'
complete -c gist -s d -l description --description 'Set a description.'
complete -c gist -s o -l '[no-]open' --description 'Open the gist in your browser after creation.  Or don\'t.'
complete -c gist -s h -l help --description 'Print help.'

