# git-update-index
# Autogenerated from man page /usr/share/man/man1/git-update-index.1
# using Deroffing man parser
complete -c git-update-index -l assume-unchanged -l no-assume-unchanged --description 'When these flags are specified, the object name… [See Man Page]'
complete -c git-update-index -l skip-worktree -l no-skip-worktree --description 'When one of these flags is specified, the objec… [See Man Page]'

