# git-check-ignore
# Autogenerated from man page /usr/local/share/man/man1/git-check-ignore.1
# using Deroffing man parser
complete -c git-check-ignore -s q -l quiet --description 'Don\\(cqt output anything, just set exit status.'
complete -c git-check-ignore -s v -l verbose --description 'Also output details about the matching pattern … [See Man Page]'
complete -c git-check-ignore -l stdin --description 'Read file names from stdin instead of from the command-line.'
complete -c git-check-ignore -s z --description 'The output format is modified to be machine-par… [See Man Page]'

