# git-daemon
# Autogenerated from man page /usr/share/man/man1/git-daemon.1
# using Deroffing man parser
complete -c git-daemon -l informative-errors -l no-informative-errors --description 'When informative errors are turned on, git-daem… [See Man Page]'

