# git-shortlog
# Autogenerated from man page /usr/share/man/man1/git-shortlog.1
# using Deroffing man parser
complete -c git-shortlog -s h -l help --description 'Print a short usage message and exit.'

