# git-fsck
# Autogenerated from man page /usr/share/man/man1/git-fsck.1
# using Deroffing man parser
complete -c git-fsck -l progress -l no-progress --description 'Progress status is reported on the standard err… [See Man Page]'

