# git-merge
# Autogenerated from man page /usr/share/man/man1/git-merge.1
# using Deroffing man parser
complete -c git-merge -l rerere-autoupdate -l no-rerere-autoupdate --description 'Allow the rerere mechanism to update the index … [See Man Page]'

