# git-format-patch
# Autogenerated from man page /usr/share/man/man1/git-format-patch.1
# using Deroffing man parser
complete -c git-format-patch -l cover-letter --description 'In addition to the patches, generate a cover le… [See Man Page]'

