# git-check-ref-format
# Autogenerated from man page /usr/share/man/man1/git-check-ref-format.1
# using Deroffing man parser
complete -c git-check-ref-format -l no-allow-onelevel --description 'Controls whether one-level refnames are accepted (i. e.'

