# git-fmt-merge-msg
# Autogenerated from man page /usr/share/man/man1/git-fmt-merge-msg.1
# using Deroffing man parser
complete -c git-fmt-merge-msg -l summary -l no-summary --description 'Synonyms to --log and --no-log; these are depre… [See Man Page]'

