# git-fast-import
# Autogenerated from man page /usr/share/man/man1/git-fast-import.1
# using Deroffing man parser
complete -c git-fast-import -l relative-marks --description 'After specifying --relative-marks the paths spe… [See Man Page]'
complete -c git-fast-import -l no-relative-marks --description 'Negates a previous --relative-marks.'

