# git-push
# Autogenerated from man page /usr/share/man/man1/git-push.1
# using Deroffing man parser
complete -c git-push -l thin -l no-thin --description 'These options are passed to git-send-pack(1).'

