# gitremote-helpers
# Autogenerated from man page /usr/local/share/man/man1/gitremote-helpers.1
# using Deroffing man parser
complete -c gitremote-helpers -l export-marks --description 'in git-fast-export(1).  import-marks <file>.'
complete -c gitremote-helpers -l import-marks --description 'in git-fast-export(1).  signed-tags.'
complete -c gitremote-helpers -l signed-tags --description 'to git-fast-export(1).'

