# gnuplot
# Autogenerated from man page /usr/local/share/man/man1/gnuplot.1
# using Deroffing man parser
complete -c gnuplot -s p -l persist --description '.'
complete -c gnuplot -s e --description '.'
complete -c gnuplot -s h -l help --description '.'
complete -c gnuplot -s V --description 'X11 OPTIONS Gnuplot provides the x11 terminal t… [See Man Page]'

