# gnutls-cli-debug
# Autogenerated from man page /usr/local/share/man/man1/gnutls-cli-debug.1
# using Type1
complete -c gnutls-cli-debug -s d -l debug --description 'Enable debugging.'
complete -c gnutls-cli-debug -s V -l verbose --description 'More verbose output.'
complete -c gnutls-cli-debug -s p -l port --description 'The port to connect to.'
complete -c gnutls-cli-debug -s h -l help --description 'Display usage information and exit.'
complete -c gnutls-cli-debug -s '!' -l more-help --description 'Pass the extended usage information through a pager.'

