# gpg-connect-agent
# Autogenerated from man page /usr/local/MacGPG2/share/man/man1/gpg-connect-agent.1
# using Deroffing man parser
complete -c gpg-connect-agent -s v --description '.'
complete -c gpg-connect-agent -l verbose --description 'Output additional information while running.'
complete -c gpg-connect-agent -s q --description '.'
complete -c gpg-connect-agent -l quiet --description 'Try to be as quiet as possible.'
complete -c gpg-connect-agent -l homedir --description 'Set the name of the home directory to dir.'
complete -c gpg-connect-agent -l agent-program --description 'Specify the agent program to be started if none is running.'
complete -c gpg-connect-agent -s S --description '.'
complete -c gpg-connect-agent -l raw-socket --description 'Connect to socket name assuming this is an Assuan style server.'
complete -c gpg-connect-agent -s E --description '.'
complete -c gpg-connect-agent -l exec --description 'Take the rest of the command line as a program … [See Man Page]'
complete -c gpg-connect-agent -l no-ext-connect --description 'When using -S or --exec, gpg-connect-agent conn… [See Man Page]'
complete -c gpg-connect-agent -l run --description 'Run the commands from file at startup and then … [See Man Page]'
complete -c gpg-connect-agent -s s --description '.'
complete -c gpg-connect-agent -l subst --description 'Run the command /subst at startup.'
complete -c gpg-connect-agent -l hex --description 'Print data lines in a hex format and the ASCII … [See Man Page]'
complete -c gpg-connect-agent -l decode --description 'Decode data lines.'

