# gpgconf
# Autogenerated from man page /usr/local/MacGPG2/share/man/man1/gpgconf.1
# using Deroffing man parser
complete -c gpgconf -l verbose --description 'Outputs additional information while running.'
complete -c gpgconf -l dry-run --description 'Do not actually change anything.'
complete -c gpgconf -l list-components --description 'List all components.'
complete -c gpgconf -l check-programs --description 'List all available backend programs and test wh… [See Man Page]'
complete -c gpgconf -l list-options --description 'List all options of the component component.'
complete -c gpgconf -l change-options --description 'Change the options of the component component.'
complete -c gpgconf -l check-options --description 'Check the options for the component component.'
complete -c gpgconf -l apply-defaults --description 'Update all configuration files with values take… [See Man Page]'
complete -c gpgconf -l list-dirs --description 'Lists the directories used by gpgconf.'
complete -c gpgconf -l list-config --description 'List the global configuration file in a colon separated format.'
complete -c gpgconf -l check-config --description 'Run a syntax check on the global configuration file.'
complete -c gpgconf -l reload --description 'Reload all or the given component.'
complete -c gpgconf -l kill --description 'Kill the given component.'
complete -c gpgconf -s v --description '.'
complete -c gpgconf -s n --description '.'
complete -c gpgconf -s r --description '.'
complete -c gpgconf -l runtime --description 'Only used together with --change-options.'

