# GraphicsMagickWand-config
# Autogenerated from man page /usr/local/share/man/man1/GraphicsMagickWand-config.1
# using Deroffing man parser
complete -c GraphicsMagickWand-config -l cflags --description 'Print the compiler flags that were used to comp… [See Man Page]'
complete -c GraphicsMagickWand-config -l cppflags --description 'Print the preprocessor flags that are needed to… [See Man Page]'
complete -c GraphicsMagickWand-config -l exec-prefix --description 'Print the directory under which target specific… [See Man Page]'
complete -c GraphicsMagickWand-config -l ldflags --description 'Print the linker flags that are needed to link … [See Man Page]'
complete -c GraphicsMagickWand-config -l libs --description 'Print the linker flags that are needed to link … [See Man Page]'
complete -c GraphicsMagickWand-config -l version --description 'Print the version of the GraphicsMagick distrib… [See Man Page]'

