# gresource
# Autogenerated from man page /usr/local/share/man/man1/gresource.1
# using Deroffing man parser
complete -c gresource -l section --description 'option.  Use the sections command to find available sections.'

