# gsnd
# Autogenerated from man page /usr/local/share/man/man1/gsnd.1
# using Deroffing man parser
complete -c gsnd -o NODISPLAY --description 'flag, followed by any other arguments from the command-line.'

