# gtester-report
# Autogenerated from man page /usr/local/share/man/man1/gtester-report.1
# using Deroffing man parser
complete -c gtester-report -s h -l help --description '.'
complete -c gtester-report -s v -l version --description '.'

