# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
# using Darwin man parser
complete -c halt -s l --description 'The halt or reboot is not recorded in the system log.'
complete -c halt -s n --description 'The file system cache is not flushed.'
complete -c halt -s q --description 'The system is halted or restarted quickly and u… [See Man Page]'
complete -c halt -s u --description 'The system is halted up until the point of remo… [See Man Page]'

