# haproxy
# Autogenerated from man page /usr/local/share/man/man1/haproxy.1
# using Deroffing man parser
complete -c haproxy -s f --description 'Specify configuration file path.'
complete -c haproxy -s n --description 'Set the high limit for the total number of simu… [See Man Page]'
complete -c haproxy -s N --description 'Set the high limit for the per-listener number … [See Man Page]'
complete -c haproxy -s d --description 'Start in foregreound with debugging mode enabled.'
complete -c haproxy -s D --description 'Start in daemon mode.'
complete -c haproxy -s q --description 'Disable messages on output.'
complete -c haproxy -s V --description 'Displays messages on output even when -q or \'qu… [See Man Page]'
complete -c haproxy -s c --description 'Only checks config file and exits with code 0 i… [See Man Page]'
complete -c haproxy -s p --description 'Ask the process to write down each of its child… [See Man Page]'
complete -c haproxy -s s --description 'Show statistics (only if compiled in).'
complete -c haproxy -s l --description 'Show even more statistics (implies \'-s\').'
complete -c haproxy -o dk --description 'Disable use of kqueue().'
complete -c haproxy -o ds --description 'Disable use of speculative epoll().'
complete -c haproxy -o de --description 'Disable use of epoll().  epoll() is available only on Linux 2.'
complete -c haproxy -o dp --description 'Disables use of poll().  select() might be used instead.'
complete -c haproxy -o db --description 'Disables background mode (stays in foreground, … [See Man Page]'
complete -c haproxy -s m --description 'Enforce a memory usage limit to a maximum of <megs> megabytes.'
complete -c haproxy -o sf --description 'Send FINISH signal to the pids in pidlist after startup.'
complete -c haproxy -o st --description 'Send TERMINATE signal to the pids in pidlist after startup.'

