# hdid
# Autogenerated from man page /usr/share/man/man8/hdid.8
# using Deroffing man parser
complete -c hdid -o 'nomount.' --description '.'
complete -c hdid -o help --description 'show available options.'
complete -c hdid -o shadow --description 'Use a shadow file in conjunction with the data in the image.'
complete -c hdid -o readonly --description 'Attach the image read only.'
complete -c hdid -o readwrite --description 'Attach the image read/write.'
complete -c hdid -o nomount --description 'Suppress automatic mounting of any filesystems in the image.'
complete -c hdid -o notremovable --description 'Make the image appear to the system as a fixed disk.'
complete -c hdid -o encryption --description 'This option specifies a particular encrypted encoding.'
complete -c hdid -o stdinpass --description 'causes hdid to read a null-terminated passphras… [See Man Page]'
complete -c hdid -o passphrase --description 'This option is provided for automation purposes… [See Man Page]'
complete -c hdid -o imagekey --description 'Specify a key/value pair for the disk image rec… [See Man Page]'
complete -c hdid -o drivekey --description 'Specify a key/value pair for the IOHDIXHDDrive … [See Man Page]'
complete -c hdid -o section --description 'Attach a subset of the disk image.'
complete -c hdid -o kernel --description 'hand the image directly to the IOHDIXController… [See Man Page]'
complete -c hdid -o nokernel --description 'attach the image with a persistent process inst… [See Man Page]'
complete -c hdid -o plist --description 'output a plist describing the image and system … [See Man Page]'
complete -c hdid -o verbose --description 'verbose output when attaching an image.'
complete -c hdid -o debug --description 'diagnostic output when attaching an image.'
complete -c hdid -o quiet --description 'Don\'t print out resulting /dev entries and filesystems.'

