# http_load
# Autogenerated from man page /usr/local/share/man/man1/http_load.1
# using Deroffing man parser
complete -c http_load -o parallel --description 'http_load to keep that many parallel fetches go… [See Man Page]'
complete -c http_load -o rate --description 'http_load to start that many new connections each second.'
complete -c http_load -o fetches --description 'http_load to quit when that many fetches have been completed.'
complete -c http_load -o seconds --description 'http_load to quit after that many seconds have elapsed.'

