# icc2ps
# Autogenerated from man page /usr/local/share/man/man1/icc2ps.1
# using Deroffing man parser
complete -c icc2ps -s b --description 'Black point compensation (CRD only).'
complete -c icc2ps -s i --description 'Input profile: Generates Color Space Array (CSA).'
complete -c icc2ps -s o --description 'p Output profile: Generates Color Rendering Dictionary(CRD).'
complete -c icc2ps -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturat… [See Man Page]'
complete -c icc2ps -s u --description 'Do NOT generate resource name on CRD.'

