# imake
# Autogenerated from man page /usr/local/share/man/man1/imake.1
# using Deroffing man parser
complete -c imake -o Ddefine --description 'This option is passed directly to cpp.'
complete -c imake -o Idirectory --description 'This option is passed directly to cpp.'
complete -c imake -o Udefine --description 'This option is passed directly to cpp.'
complete -c imake -o Ttemplate --description 'This option specifies the name of the master te… [See Man Page]'
complete -c imake -s f --description 'This option specifies the name of the per-directory input file.'
complete -c imake -s C --description 'This option specifies the name of the .'
complete -c imake -s s --description 'This option specifies the name of the make desc… [See Man Page]'
complete -c imake -s e --description 'This option indicates the imake should execute … [See Man Page]'
complete -c imake -s v --description 'This option indicates that imake should print t… [See Man Page]'
complete -c imake -s T --description '.'

