# innochecksum
# Autogenerated from man page /usr/local/share/man/man1/innochecksum.1
# using Deroffing man parser
complete -c innochecksum -s c --description '.'
complete -c innochecksum -s d --description '.'
complete -c innochecksum -s e --description '.'
complete -c innochecksum -s p --description '.'
complete -c innochecksum -s s --description '.'
complete -c innochecksum -s v --description '.'

