# ip6
# Autogenerated from man page /usr/share/man/man8/ip6.8
# using Darwin man parser
complete -c ip6 -s a --description 'Start IPv6 on all interfaces.'
complete -c ip6 -s x --description 'Stop IPv6 on all interfaces.'
complete -c ip6 -s u --description 'Start IPv6 on interface.'
complete -c ip6 -s d --description 'Stop IPv6 on interface.'

