# ip6fw
# Autogenerated from man page /usr/share/man/man8/ip6fw.8
# using Darwin man parser
complete -c ip6fw -s a --description 'While listing, show counter values.   See also show command.'
complete -c ip6fw -s f --description 'Don\'t ask for confirmation for commands that ca… [See Man Page]'
complete -c ip6fw -s q --description 'While adding, zeroing or flushing, be quiet abo… [See Man Page]'
complete -c ip6fw -s t --description 'While listing, show last match timestamp.'
complete -c ip6fw -s N --description 'Try to resolve addresses and service names in output.'

