# ipfw
# Autogenerated from man page /usr/share/man/man8/ipfw.8
# using Darwin man parser
complete -c ipfw -s a --description 'While listing, show counter values.'
complete -c ipfw -s c --description 'When entering or showing rules, print them in compact form, i.'
complete -c ipfw -s d --description 'While listing, show dynamic rules in addition to static ones.'
complete -c ipfw -s e --description 'While listing, if the d option was specified, a… [See Man Page]'
complete -c ipfw -s f --description 'Don\'t ask for confirmation for commands that ca… [See Man Page]'
complete -c ipfw -s n --description 'Only check syntax of the command strings, witho… [See Man Page]'
complete -c ipfw -s N --description 'Try to resolve addresses and service names in output.'
complete -c ipfw -s q --description 'While add Ns ing, zero Ns ing, resetlog Ns ging… [See Man Page]'
complete -c ipfw -s S --description 'While listing rules, show the set each rule belongs to.'
complete -c ipfw -s s --description 'While listing pipes, sort according to one of t… [See Man Page]'
complete -c ipfw -s t --description 'While listing, show last match timestamp (conve… [See Man Page]'
complete -c ipfw -s T --description 'While listing, show last match timestamp (as se… [See Man Page]'

