# jbig2dec
# Autogenerated from man page /usr/local/share/man/man1/jbig2dec.1
# using Deroffing man parser
complete -c jbig2dec -s o --description 'Store the decoded output in R file .'
complete -c jbig2dec -s t --description 'Force a particular output file format.'
complete -c jbig2dec -s d -l dump --description 'Print the structure of the JBIG2 file rather th… [See Man Page]'
complete -c jbig2dec -l hash --description 'Print a hash of the decoded document.'
complete -c jbig2dec -s q -l quiet --description 'Suppress warnings and other diagnostic output.'
complete -c jbig2dec -s v -l verbose --description 'Report additional information about the decoding process.'
complete -c jbig2dec -l version --description 'Show program version information.'
complete -c jbig2dec -s h -l help --description 'Show usage summary.'

