# jpgicc
# Autogenerated from man page /usr/local/share/man/man1/jpgicc.1
# using Deroffing man parser
complete -c jpgicc -s b --description 'Black point compensation.'
complete -c jpgicc -s c --description 'Precalculates transform.'
complete -c jpgicc -s g --description 'Marks out-of-gamut colors on softproof.'
complete -c jpgicc -s h --description 'Show summary of options and examples.'
complete -c jpgicc -s i --description 'Input profile (defaults to sRGB).'
complete -c jpgicc -s m --description 'SoftProof intent.'
complete -c jpgicc -s n --description 'Ignore embedded profile.'
complete -c jpgicc -s p --description 'Soft proof profile.'
complete -c jpgicc -s o --description 'p Output profile (defaults to sRGB).'
complete -c jpgicc -s q --description 'Output JPEG quality.'
complete -c jpgicc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturat… [See Man Page]'
complete -c jpgicc -s v --description 'Verbose.  EXAMPLES.'

