# kdc
# Autogenerated from man page /usr/share/man/man8/kdc.8
# using Darwin man parser
complete -c kdc -l addresses --description 'The list of addresses to listen for requests on.'
complete -c kdc -l detach --description 'detach from pty and run as a daemon.'
complete -c kdc -l disable-des --description 'disable add des encryption types, makes the kdc not use them.'

