# kdcsetup
# Autogenerated from man page /usr/share/man/man8/kdcsetup.8
# using Darwin man parser
complete -c kdcsetup -s e --description 'Eanbles krb5kdc and kadmind in the launchd conf… [See Man Page]'
complete -c kdcsetup -s d --description 'Disables krb5kdc and kadmind in the launchd con… [See Man Page]'
complete -c kdcsetup -s f --description 'Create a "master" KDC, write the KerberosKDC an… [See Man Page]'
complete -c kdcsetup -s c --description 'Create a "replica" KDC, read the KerberosKDC re… [See Man Page]'
complete -c kdcsetup -s x --description 'Promotes a replica KDC to a master.'
complete -c kdcsetup -s w --description 'Add krb5kdc and kadmind to the launchd config.'
complete -c kdcsetup -s a --description 'Name of an administrator authorized to make cha… [See Man Page]'
complete -c kdcsetup -s p --description 'The password for the above admin REALM The real… [See Man Page]'

