# lua
# Autogenerated from man page /usr/local/share/man/man1/lua.1
# using Deroffing man parser
complete -c lua -s e --description 'execute statement R stat .'
complete -c lua -s i --description 'enter interactive mode after  script is executed.'
complete -c lua -s l --description 'call  require(\' name \') before executing R script .'
complete -c lua -s v --description 'is assumed when the standard input is a terminal; otherwise,.'

