# lwresd
# Autogenerated from man page /usr/share/man/man8/lwresd.8.gz
# using Deroffing man parser
complete -c lwresd -s 4 --description 'Use IPv4 only even if the host machine is capable of IPv6.'
complete -c lwresd -s 6 --description 'Use IPv6 only even if the host machine is capable of IPv4.'
complete -c lwresd -s c --description 'Use config-file as the configuration file inste… [See Man Page]'
complete -c lwresd -s C --description 'Use config-file as the configuration file inste… [See Man Page]'
complete -c lwresd -s d --description 'Set the daemon\'s debug level to debug-level.'
complete -c lwresd -s f --description 'Run the server in the foreground (i. e.  do not daemonize).'
complete -c lwresd -s g --description 'Run the server in the foreground and force all … [See Man Page]'
complete -c lwresd -s i --description 'Use pid-file as the PID file instead of the def… [See Man Page]'
complete -c lwresd -s m --description 'Turn on memory usage debugging flags.'
complete -c lwresd -s n --description 'Create #cpus worker threads to take advantage of multiple CPUs.'
complete -c lwresd -s P --description 'Listen for lightweight resolver queries on port port.'
complete -c lwresd -s p --description 'Send DNS lookups to port port.'
complete -c lwresd -s s --description 'Write memory usage statistics to stdout on exit.'
complete -c lwresd -s t --description 'Chroot to directory after processing the comman… [See Man Page]'
complete -c lwresd -s u --description 'Setuid to user after completing privileged oper… [See Man Page]'
complete -c lwresd -s v --description 'Report the version number and exit.'
complete -c lwresd -o 'C.' --description '.'
complete -c lwresd -o 'c.' --description '.'

