# makedbm
# Autogenerated from man page /usr/share/man/man8/makedbm.8.gz
# using Darwin man parser
complete -c makedbm -s u --description 'Dump a database to standard output.'
complete -c makedbm -s U --description 'Same as u but also try db 3 hash format.'
complete -c makedbm -s b --description 'Interdomain.'
complete -c makedbm -s l --description 'Lowercase.'
complete -c makedbm -s s --description 'Secure map.'
complete -c makedbm -s i --description 'Include an entry the in the map with the key YP… [See Man Page]'
complete -c makedbm -s o --description 'Include an entry the in the map with the key YP… [See Man Page]'
complete -c makedbm -s d --description 'Include an entry the in the map with the key YP… [See Man Page]'
complete -c makedbm -s m --description 'Include an entry the in the map with the key YP… [See Man Page]'

