# MucDataMigrator
# Autogenerated from man page /usr/share/man/man8/MucDataMigrator.8
# using Darwin man parser
complete -c MucDataMigrator -s s --description 'Path to the source mu-conference spool director… [See Man Page]'
complete -c MucDataMigrator -s d --description 'Path to the destination Rooms data directory (required) (ex.'
complete -c MucDataMigrator -s v --description 'Enable verbose output \\" Ends the list Pp .'

