# myisam_ftdump
# Autogenerated from man page /usr/local/share/man/man1/myisam_ftdump.1
# using Deroffing man parser
complete -c myisam_ftdump -l help --description '.'
complete -c myisam_ftdump -s h --description '.'
complete -c myisam_ftdump -s '?' --description '.'
complete -c myisam_ftdump -l count --description '.'
complete -c myisam_ftdump -s c --description '.'
complete -c myisam_ftdump -l dump --description '.'
complete -c myisam_ftdump -s d --description '.'
complete -c myisam_ftdump -l length --description '.'
complete -c myisam_ftdump -s l --description '.'
complete -c myisam_ftdump -l stats --description '.'
complete -c myisam_ftdump -s s --description '.'
complete -c myisam_ftdump -l verbose --description '.'
complete -c myisam_ftdump -s v --description '.'

