# mysql_find_rows
# Autogenerated from man page /usr/local/share/man/man1/mysql_find_rows.1
# using Deroffing man parser
complete -c mysql_find_rows -l help --description '.'
complete -c mysql_find_rows -l Information --description '.'
complete -c mysql_find_rows -l regexp --description '.'
complete -c mysql_find_rows -l rows --description '.'
complete -c mysql_find_rows -l skip-use-db --description '.'
complete -c mysql_find_rows -l start_row --description '.'

