# mysql_setpermission
# Autogenerated from man page /usr/local/share/man/man1/mysql_setpermission.1
# using Deroffing man parser
complete -c mysql_setpermission -l help --description 'to display the help message, or options that in… [See Man Page]'
complete -c mysql_setpermission -l host --description '.'
complete -c mysql_setpermission -l password --description '.'
complete -c mysql_setpermission -l port --description '.'
complete -c mysql_setpermission -l socket --description '.'
complete -c mysql_setpermission -l user --description '.'

