# mysqld_multi
# Autogenerated from man page /usr/local/share/man/man1/mysqld_multi.1
# using Deroffing man parser
complete -c mysqld_multi -l config-file --description 'option).  N can be any positive integer.'
complete -c mysqld_multi -l no-defaults --description 'oc o 2. 3 With.'
complete -c mysqld_multi -l defaults-file --description 'oc o 2.'
complete -c mysqld_multi -l defaults-extra-file --description 'option, if one is given.'
complete -c mysqld_multi -l help --description '.'
complete -c mysqld_multi -l example --description '.'
complete -c mysqld_multi -l log --description '.'
complete -c mysqld_multi -l mysqladmin --description '.'
complete -c mysqld_multi -l mysqld --description '.'
complete -c mysqld_multi -l no-log --description '.'
complete -c mysqld_multi -l password --description '.'
complete -c mysqld_multi -l silent --description '.'
complete -c mysqld_multi -l tcp-ip --description '.'
complete -c mysqld_multi -l user --description '.'
complete -c mysqld_multi -l verbose --description '.'
complete -c mysqld_multi -l version --description '.'
complete -c mysqld_multi -l bind-address --description 'to cause different servers to listen to different interfaces.'
complete -c mysqld_multi -l pid-file --description 'option is very important if you are using mysql… [See Man Page]'
complete -c mysqld_multi -l -------------------------------------------------------------- --description 'MY_PWD=`pwd` # Check if we are starting this re… [See Man Page]'

