# mysql_waitpid
# Autogenerated from man page /usr/local/share/man/man1/mysql_waitpid.1
# using Deroffing man parser
complete -c mysql_waitpid -l help --description '.'
complete -c mysql_waitpid -s '?' --description '.'
complete -c mysql_waitpid -s I --description '.'
complete -c mysql_waitpid -l verbose --description '.'
complete -c mysql_waitpid -s v --description '.'
complete -c mysql_waitpid -l version --description '.'
complete -c mysql_waitpid -s V --description '.'

