# mysql_config
# Autogenerated from man page /usr/local/share/man/man1/mysql_config.1
# using Deroffing man parser
complete -c mysql_config -l cflags --description '.'
complete -c mysql_config -l include --description 'for more portable options that contain only include paths.'
complete -c mysql_config -l cxxflags --description '.'
complete -c mysql_config -l libmysqld-libs --description '.'
complete -c mysql_config -l embedded --description '.'
complete -c mysql_config -l libs --description '.'
complete -c mysql_config -l libs_r --description '.'
complete -c mysql_config -l plugindir --description '.'
complete -c mysql_config -l port --description '.'
complete -c mysql_config -l socket --description '.'
complete -c mysql_config -l version --description '.'

