# mysql_zap
# Autogenerated from man page /usr/local/share/man/man1/mysql_zap.1
# using Deroffing man parser
complete -c mysql_zap -o signal --description 'option is given, it specifies the name or numbe… [See Man Page]'
complete -c mysql_zap -l help --description '.'
complete -c mysql_zap -s '?' --description '.'
complete -c mysql_zap -s I --description '.'
complete -c mysql_zap -s f --description '.'
complete -c mysql_zap -s t --description '.'

