# named
# Autogenerated from man page /usr/share/man/man8/named.8.gz
# using Deroffing man parser
complete -c named -s 4 --description 'Use IPv4 only even if the host machine is capable of IPv6.'
complete -c named -s 6 --description 'Use IPv6 only even if the host machine is capable of IPv4.'
complete -c named -s c --description 'Use config-file as the configuration file inste… [See Man Page]'
complete -c named -s d --description 'Set the daemon\'s debug level to debug-level.'
complete -c named -s E --description 'Use a crypto hardware (OpenSSL engine) for the … [See Man Page]'
complete -c named -s f --description 'Run the server in the foreground (i. e.  do not daemonize).'
complete -c named -s g --description 'Run the server in the foreground and force all … [See Man Page]'
complete -c named -s m --description 'Turn on memory usage debugging flags.'
complete -c named -s n --description 'Create #cpus worker threads to take advantage of multiple CPUs.'
complete -c named -s p --description 'Listen for queries on port port.'
complete -c named -s s --description 'Write memory usage statistics to stdout on exit.'
complete -c named -s S --description 'Allow named to use up to #max-socks sockets.'
complete -c named -s t --description 'Chroot to directory after processing the comman… [See Man Page]'
complete -c named -s u --description 'Setuid to user after completing privileged oper… [See Man Page]'
complete -c named -s v --description 'Report the version number and exit.'
complete -c named -s V --description 'Report the version number and build options, and exit.'
complete -c named -s x --description 'Load data from cache-file into the cache of the default view.'

