# named-checkconf
# Autogenerated from man page /usr/share/man/man8/named-checkconf.8.gz
# using Deroffing man parser
complete -c named-checkconf -s h --description 'Print the usage summary and exit.'
complete -c named-checkconf -s t --description 'Chroot to directory so that include directives … [See Man Page]'
complete -c named-checkconf -s v --description 'Print the version of the named-checkconf program and exit.'
complete -c named-checkconf -s p --description 'Print out the named.'
complete -c named-checkconf -s z --description 'Perform a test load of all master zones found in named. conf.'
complete -c named-checkconf -s j --description 'When loading a zonefile read the journal if it exists.'

