# ndiff
# Autogenerated from man page /usr/local/share/man/man1/ndiff.1
# using Deroffing man parser
complete -c ndiff -o 'sV)' --description 'oc o 2. 3.'
complete -c ndiff -o 'O)' --description 'oc o 2. 3.'
complete -c ndiff -s h -l help --description '.'
complete -c ndiff -s v -l verbose --description '.'
complete -c ndiff -l text --description '.'
complete -c ndiff -l xml --description '.'
complete -c ndiff -o Nmap --description '+Nmap 5. 35DC1 at 2010-07-16 12:13.'
complete -c ndiff -o Not --description '+Not shown: 993 filtered ports  PORT      STATE… [See Man Page]'
complete -c ndiff -s F --description 'fast scan option found two additional ports: 70 and 31337.'
complete -c ndiff -l 'verbose)' --description '.'
complete -c ndiff -o 80/tcp --description '+80/tcp open  http    lighttpd 1. 5. 0.'
complete -c ndiff -o 'cm.out.snc1.tfbnw.net' --description '+mailout-snc1. facebook. com (69. 63. 179. 25):  Host is up.'

