# nginx
# Autogenerated from man page /usr/local/share/man/man8/nginx.8
# using Darwin man parser
complete -c nginx -s '?' --description 'Print help.'
complete -c nginx -s c --description 'Use an alternative configuration file.'
complete -c nginx -s g --description 'Set global configuration directives.  See EXAMPLES for details.'
complete -c nginx -s p --description 'Set the prefix path.'
complete -c nginx -s q --description 'Suppress non-error messages during configuration testing.'
complete -c nginx -s s --description 'Send a signal to the master process.'
complete -c nginx -s t --description 'Do not run, just test the configuration file.'
complete -c nginx -s V --description 'Print the nginx version, compiler version, and … [See Man Page]'
complete -c nginx -s v --description 'Print the nginx version.'

