# nmap-update
# Autogenerated from man page /usr/local/share/man/man1/nmap-update.1
# using Deroffing man parser
complete -c nmap-update -s d --description '.'
complete -c nmap-update -s h -l help --description '.'
complete -c nmap-update -s r -l repo --description '.'
complete -c nmap-update -l username --description '.'
complete -c nmap-update -l password --description '.'
complete -c nmap-update -s v -l verbose --description '.'

