# npm-config
# Autogenerated from man page /usr/local/share/man/man1/npm-config.1
# using Deroffing man parser
complete -c npm-config -o v: -l version --description '.'
complete -c npm-config -s h -s '?' -l help -o H: -l usage --description '.'
complete -c npm-config -s s -l silent: -l loglevel --description '.'
complete -c npm-config -s q -l quiet: --description '.'
complete -c npm-config -o d: --description '.'
complete -c npm-config -o dd -l verbose: --description '.'
complete -c npm-config -o ddd: --description '.'
complete -c npm-config -o g: -l global --description '.'
complete -c npm-config -o l: -l long --description '.'
complete -c npm-config -o m: -l message --description '.'
complete -c npm-config -s p -l porcelain: -l parseable --description '.'
complete -c npm-config -o reg: -l registry --description '.'
complete -c npm-config -o f: -l force --description '.'
complete -c npm-config -o desc: -l description --description '.'
complete -c npm-config -o S: -l save --description '.'
complete -c npm-config -o D: -l save-dev --description '.'
complete -c npm-config -o O: -l save-optional --description '.'
complete -c npm-config -o B: -l save-bundle --description '.'
complete -c npm-config -o y: -l yes --description '.'
complete -c npm-config -o n: --description '.'

