# npm-set
# Autogenerated from man page /usr/local/share/man/man1/npm-set.1
# using Deroffing man parser
complete -c npm-set -o v: -l version --description '.'
complete -c npm-set -s h -s '?' -l help -o H: -l usage --description '.'
complete -c npm-set -s s -l silent: -l loglevel --description '.'
complete -c npm-set -o d: --description '.'
complete -c npm-set -o dd -l verbose: --description '.'
complete -c npm-set -o ddd: --description '.'
complete -c npm-set -o g: -l global --description '.'
complete -c npm-set -o l: -l long --description '.'
complete -c npm-set -o m: -l message --description '.'
complete -c npm-set -s p -l porcelain: -l parseable --description '.'
complete -c npm-set -o reg: -l registry --description '.'
complete -c npm-set -o f: -l force --description '.'
complete -c npm-set -o desc: -l description --description '.'
complete -c npm-set -o S: -l save --description '.'
complete -c npm-set -o y: -l yes --description '.'
complete -c npm-set -o n: --description '.'

