# npm-get
# Autogenerated from man page /usr/local/share/man/man1/npm-get.1
# using Deroffing man parser
complete -c npm-get -o v: -l version --description '.'
complete -c npm-get -s h -s '?' -l help -o H: -l usage --description '.'
complete -c npm-get -s s -l silent: -l loglevel --description '.'
complete -c npm-get -o d: --description '.'
complete -c npm-get -o dd -l verbose: --description '.'
complete -c npm-get -o ddd: --description '.'
complete -c npm-get -o g: -l global --description '.'
complete -c npm-get -o l: -l long --description '.'
complete -c npm-get -o m: -l message --description '.'
complete -c npm-get -s p -l porcelain: -l parseable --description '.'
complete -c npm-get -o reg: -l registry --description '.'
complete -c npm-get -o f: -l force --description '.'
complete -c npm-get -o desc: -l description --description '.'
complete -c npm-get -o S: -l save --description '.'
complete -c npm-get -o y: -l yes --description '.'
complete -c npm-get -o n: --description '.'

