# ocsptool
# Autogenerated from man page /usr/local/share/man/man1/ocsptool.1
# using Type1
complete -c ocsptool -s d -l debug --description 'Enable debugging.'
complete -c ocsptool -s V -l verbose --description 'More verbose output.'
complete -c ocsptool -l infile --description 'Input file. sp.'
complete -c ocsptool -l outfile --description 'Output file. sp.'
complete -c ocsptool -l ask --description 'Ask an OCSP/HTTP server on a certificate validity.'
complete -c ocsptool -s e -l verify-response --description 'Verify response. sp.'
complete -c ocsptool -s i -l request-info --description 'Print information on a OCSP request. sp.'
complete -c ocsptool -s j -l response-info --description 'Print information on a OCSP response. sp.'
complete -c ocsptool -s q -l generate-request --description 'Generate an OCSP request. sp.'
complete -c ocsptool -l nonce -l no-nonce --description 'Don\'t add nonce to OCSP request.'
complete -c ocsptool -l load-issuer --description 'Read issuer certificate from file. sp.'
complete -c ocsptool -l load-cert --description 'Read certificate to check from file. sp.'
complete -c ocsptool -l load-trust --description 'Read OCSP trust anchors from file.'
complete -c ocsptool -l load-signer --description 'Read OCSP response signer from file.'
complete -c ocsptool -l inder -l no-inder --description 'Use DER format for input certificates and private keys.'
complete -c ocsptool -s Q -l load-request --description 'Read DER encoded OCSP request from file. sp.'
complete -c ocsptool -s S -l load-response --description 'Read DER encoded OCSP response from file. sp.'
complete -c ocsptool -s h -l help --description 'Display usage information and exit.'
complete -c ocsptool -s '!' -l more-help --description 'Pass the extended usage information through a pager.'

