# pcastagentd
# Autogenerated from man page /usr/share/man/man8/pcastagentd.8
# using Darwin man parser
complete -c pcastagentd -s d --description 'duration in seconds for an ad-hoc recording.'
complete -c pcastagentd -s f --description 'file_output_path (runs an ad-hoc capture on this machine).'
complete -c pcastagentd -s h --description 'display usage.'
complete -c pcastagentd -s i --description 'display information of the requested type.'
complete -c pcastagentd -s s --description 'disables submission post-process step, enabled by default.'
complete -c pcastagentd -s v --description 'display version El sp SEE ALSO podcast 1.'

