# pcscd
# Autogenerated from man page /usr/share/man/man8/pcscd.8
# using Deroffing man parser
complete -c pcscd -s a -l apdu --description 'log APDUs and SW using the debug method (see -d).'
complete -c pcscd -s c -l config --description 'Specifies the file file as an alternate location for reader.'
complete -c pcscd -s d -l debug --description 'display debug messages.'
complete -c pcscd -s f -l foreground --description 'Runs pcscd in the foreground (no daemon).'
complete -c pcscd -s h -l help --description 'Displays information about the pcscd command line.'
complete -c pcscd -s v -l version --description 'Displays the program version number DESCRIPTION… [See Man Page]'

