# pgrep
# Autogenerated from man page /usr/local/share/man/man1/pgrep.1
# using Darwin man parser
complete -c pgrep -s d --description 'Use the specified delimiter to separate the pro… [See Man Page]'
complete -c pgrep -s f --description 'Match the pattern anywhere in the full argument… [See Man Page]'
complete -c pgrep -s g --description 'Match only processes that exist within the proc… [See Man Page]'
complete -c pgrep -s G --description 'Match only processes whose real group ID is listed.'
complete -c pgrep -s i --description 'Use case-insensitive pattern matching.'
complete -c pgrep -s l --description 'Print the executable name of the process along … [See Man Page]'
complete -c pgrep -s L --description 'Print the full argument string of the process a… [See Man Page]'
complete -c pgrep -s n --description 'Print only the latest process that matches the … [See Man Page]'
complete -c pgrep -s P --description 'Match only processes whose parent process ID is specified.'
complete -c pgrep -s t --description 'Match only processes whose controlling terminal is specified.'
complete -c pgrep -s u --description 'Match only processes whose effective user ID is given.'
complete -c pgrep -s U --description 'Match only processes whose real user ID is given.'
complete -c pgrep -s v --description 'Invert the matching algorithm.'
complete -c pgrep -s V --description 'Prints the pgrep version, then quits.'
complete -c pgrep -s x --description 'Treat the pattern as a literal string for exact… [See Man Page]'

