# pidof
# Autogenerated from man page /usr/local/share/man/man1/pidof.1.gz
# using Deroffing man parser
complete -c pidof -s l --description 'prints output in long format, rather than just PID numbers.'
complete -c pidof -s k --description 'kill process(es) by name.'
complete -c pidof -s h -s '?' --description 'print out help.'
complete -c pidof -s v --description 'prints out version info on pidof.'

