# pkill
# Autogenerated from man page /usr/local/share/man/man1/pkill.1
# using Darwin man parser
complete -c pkill -o signal --description 'Specifies the signal to be sent to the matched processes.'
complete -c pkill -s f --description 'Match the pattern anywhere in the full argument… [See Man Page]'
complete -c pkill -s g --description 'Match only processes that exist within the proc… [See Man Page]'
complete -c pkill -s G --description 'Match only processes whose real group ID is listed.'
complete -c pkill -s i --description 'Use case-insensitive pattern matching.'
complete -c pkill -s l --description 'Print the executable name of the process along … [See Man Page]'
complete -c pkill -s n --description 'Print only the latest process that matches the … [See Man Page]'
complete -c pkill -s P --description 'Match only processes whose parent process ID is specified.'
complete -c pkill -s s --description 'Specifies the signal to be sent to the matched processes.'
complete -c pkill -s t --description 'Match only processes whose controlling terminal is specified.'
complete -c pkill -s u --description 'Match only processes whose effective user ID is given.'
complete -c pkill -s U --description 'Match only processes whose real user ID is given.'
complete -c pkill -s v --description 'Invert the matching algorithm.'
complete -c pkill -s V --description 'Prints the pkill version, then quits.'
complete -c pkill -s x --description 'Treat the pattern as a literal string for exact… [See Man Page]'

