# plainrsa-gen
# Autogenerated from man page /usr/share/man/man8/plainrsa-gen.8
# using Darwin man parser
complete -c plainrsa-gen -s b --description 'bit length of the key.'
complete -c plainrsa-gen -s e --description 'value of the RSA public exponent.  Default is 0x3.'
complete -c plainrsa-gen -s f --description 'write the resulting key to outfile instead of stdout.'

