# prune
# Autogenerated from man page /usr/local/share/man/man1/prune.1
# using Deroffing man parser
complete -c prune -s n --description 'Specifies name of node to prune.'
complete -c prune -s N --description 'Specifies attribute that will be set (or change… [See Man Page]'

