# ps2pdf14
# Autogenerated from man page /usr/local/share/man/man1/ps2pdf14.1
# using Deroffing man parser
complete -c ps2pdf14 -o dCompatibility --description 'switch in the command line.'
complete -c ps2pdf14 -o dPDFSETTINGS --description 'figure. ps proof. pdf.'
complete -c ps2pdf14 -s t --description 'ps2pdf.'

