# ps2pdf12
# Autogenerated from man page /usr/local/share/man/man1/ps2pdf12.1
# using Deroffing man parser
complete -c ps2pdf12 -o dCompatibility --description 'switch in the command line.'
complete -c ps2pdf12 -o dPDFSETTINGS --description 'figure. ps proof. pdf.'
complete -c ps2pdf12 -s t --description 'ps2pdf.'

