# ps2pdf
# Autogenerated from man page /usr/local/share/man/man1/ps2pdf.1
# using Deroffing man parser
complete -c ps2pdf -o dCompatibility --description 'switch in the command line.'
complete -c ps2pdf -o dPDFSETTINGS --description 'figure. ps proof. pdf.'
complete -c ps2pdf -s t --description 'ps2pdf.'

