# psktool
# Autogenerated from man page /usr/local/share/man/man1/psktool.1
# using Type1
complete -c psktool -s d -l debug --description 'Enable debugging.'
complete -c psktool -s s -l keysize --description 'specify the key size in bytes.'
complete -c psktool -s u -l username --description 'specify a username. sp.'
complete -c psktool -s p -l passwd --description 'specify a password file. sp.'
complete -c psktool -s h -l help --description 'Display usage information and exit.'
complete -c psktool -s '!' -l more-help --description 'Pass the extended usage information through a pager.'

