# quartz-wm
# Autogenerated from man page /usr/share/man/man1/quartz-wm.1.gz
# using Darwin man parser
complete -c quartz-wm -l only-proxy --description 'This option indicates that the program should n… [See Man Page]'
complete -c quartz-wm -l no-pasteboard --description 'This option indicates that the program should n… [See Man Page]'

