# rabbitmq-plugins
# Autogenerated from man page /usr/local/share/man/man1/rabbitmq-plugins.1.gz
# using Deroffing man parser
complete -c rabbitmq-plugins -s v --description '.'
complete -c rabbitmq-plugins -s m --description '.'
complete -c rabbitmq-plugins -s E --description '.'
complete -c rabbitmq-plugins -s e --description '.'

