# rabbitmq-server
# Autogenerated from man page /usr/local/share/man/man1/rabbitmq-server.1.gz
# using Deroffing man parser
complete -c rabbitmq-server -o detached --description 'Start the server process in the background.'

