# rabbitmqctl
# Autogenerated from man page /usr/local/share/man/man1/rabbitmqctl.1.gz
# using Deroffing man parser
complete -c rabbitmqctl -l ram --description 'flag.'
complete -c rabbitmqctl -l offline --description 'flag.'

