# reject
# Autogenerated from man page /usr/share/man/man8/reject.8.gz
# using Deroffing man parser
complete -c reject -s E --description 'br Forces encryption when connecting to the server.'
complete -c reject -s U --description 'br Sets the username that is sent when connecti… [See Man Page]'
complete -c reject -s h --description 'br Chooses an alternate server.'
complete -c reject -s r --description '.'

