# resolveip
# Autogenerated from man page /usr/local/share/man/man1/resolveip.1
# using Deroffing man parser
complete -c resolveip -l help --description '.'
complete -c resolveip -l info --description '.'
complete -c resolveip -s '?' --description '.'
complete -c resolveip -s I --description '.'
complete -c resolveip -l silent --description '.'
complete -c resolveip -s s --description '.'
complete -c resolveip -l version --description '.'
complete -c resolveip -s V --description '.'

