# rndc-confgen
# Autogenerated from man page /usr/share/man/man8/rndc-confgen.8.gz
# using Deroffing man parser
complete -c rndc-confgen -s a --description 'Do automatic rndc configuration.  This creates a file rndc.'
complete -c rndc-confgen -s b --description 'Specifies the size of the authentication key in bits.'
complete -c rndc-confgen -s c --description 'Used with the -a option to specify an alternate… [See Man Page]'
complete -c rndc-confgen -s h --description 'Prints a short summary of the options and argum… [See Man Page]'
complete -c rndc-confgen -s k --description 'Specifies the key name of the rndc authentication key.'
complete -c rndc-confgen -s p --description 'Specifies the command channel port where named … [See Man Page]'
complete -c rndc-confgen -s r --description 'Specifies a source of random data for generatin… [See Man Page]'
complete -c rndc-confgen -s s --description 'Specifies the IP address where named listens fo… [See Man Page]'
complete -c rndc-confgen -s t --description 'Used with the -a option to specify a directory … [See Man Page]'
complete -c rndc-confgen -s u --description 'Used with the -a option to set the owner of the rndc.'

