# rndc
# Autogenerated from man page /usr/share/man/man8/rndc.8.gz
# using Deroffing man parser
complete -c rndc -s b --description 'Use source-address as the source address for th… [See Man Page]'
complete -c rndc -s c --description 'Use config-file as the configuration file inste… [See Man Page]'
complete -c rndc -s k --description 'Use key-file as the key file instead of the default, /etc/rndc.'
complete -c rndc -s s --description 'server is the name or address of the server whi… [See Man Page]'
complete -c rndc -s p --description 'Send commands to TCP port port instead of BIND … [See Man Page]'
complete -c rndc -s V --description 'Enable verbose logging.'
complete -c rndc -s y --description 'Use the key key_id from the configuration file.'

