# Rooms
# Autogenerated from man page /usr/share/man/man8/Rooms.8
# using Darwin man parser
complete -c Rooms -s c --description 'Path to the service configuration file.'
complete -c Rooms -s D --description 'Execute in Debug mode.'
complete -c Rooms -s v --description 'Show version string \\" Ends the list Pp .'

