# rpc
# Autogenerated from man page /usr/share/man/man8/rpc.yppasswdd.8.gz
# using Darwin man parser
complete -c rpc -o noshell --description 'Don\'t allow changes of the shell field in the passwd file.'
complete -c rpc -o nogecos --description 'Don\'t allow changes of the gecos field in the passwd file.'
complete -c rpc -o nopw --description 'Don\'t allow changes of the password in the passwd file.'
complete -c rpc -s m --description 'Don\'t use /var/yp/securenet.'

