# rpdcp
# Autogenerated from man page /usr/local/share/man/man1/rpdcp.1
# using Deroffing man parser
complete -c rpdcp -s h -s V --description '.'
complete -c rpdcp -s w --description 'Target and or filter the specified list of hosts.'
complete -c rpdcp -s x --description 'Exclude the specified hosts.'
complete -c rpdcp -s q --description 'List option values and the target nodelist and … [See Man Page]'
complete -c rpdcp -s b --description 'Disable ctrl-C status feature so that a single … [See Man Page]'
complete -c rpdcp -s r --description 'Copy directories recursively.'
complete -c rpdcp -s p --description 'Preserve modification time and modes.'
complete -c rpdcp -s e --description 'Explicitly specify path to remote pdcp binary i… [See Man Page]'
complete -c rpdcp -s l --description 'This option may be used to copy files as anothe… [See Man Page]'
complete -c rpdcp -s t --description 'Set the connect timeout.  Default is 10 seconds.'
complete -c rpdcp -s f --description 'Set the maximum number of simultaneous remote copies to number.'
complete -c rpdcp -s R --description 'Set rcmd module to name.'
complete -c rpdcp -s M --description 'When multiple misc modules provide the same opt… [See Man Page]'
complete -c rpdcp -s L --description 'List info on all loaded pdcp modules and quit.'
complete -c rpdcp -s d --description 'Include more complete thread status when SIGINT… [See Man Page]'

