# rtadvd
# Autogenerated from man page /usr/share/man/man8/rtadvd.8
# using Darwin man parser
complete -c rtadvd -s c --description 'Specify an alternate location, configfile, for … [See Man Page]'
complete -c rtadvd -s d --description 'Print debugging information.'
complete -c rtadvd -s D --description 'Even more debugging information is printed.'
complete -c rtadvd -s f --description 'Foreground mode (useful when debugging).'
complete -c rtadvd -s M --description 'Specify an interface to join the all-routers si… [See Man Page]'
complete -c rtadvd -s R --description 'Accept router renumbering requests.'
complete -c rtadvd -s s --description 'Do not add or delete prefixes dynamically.'

