# rtspproxy
# Autogenerated from man page /usr/share/man/man8/rtspproxy.8
# using Darwin man parser
complete -c rtspproxy -s p --description 'Set the port for RTSP streaming.  Well known port is 554.'

