# runsvdir
# Autogenerated from man page /usr/local/share/man/man8/runsvdir.8
# using Deroffing man parser
complete -c runsvdir -s P --description 'use setsid (2) to run each runsv (8) process in… [See Man Page]'

