# sasldblistusers2
# Autogenerated from man page /usr/share/man/man8/sasldblistusers2.8
# using Deroffing man parser
complete -c sasldblistusers2 -s f --description 'use  file for sasldb.'
complete -c sasldblistusers2 -s v --description 'Print libsasl2 version number and exit.'

