# saslauthd
# Autogenerated from man page /usr/share/man/man8/saslauthd.8
# using Darwin man parser
complete -c saslauthd -s a --description 'Use authmech as the authentication mechanism.'
complete -c saslauthd -s O --description 'A mechanism specific option (e. g.'
complete -c saslauthd -s H --description 'The remote host to be contacted by the rimap au… [See Man Page]'
complete -c saslauthd -s m --description 'Use path as the pathname to the named socket to… [See Man Page]'
complete -c saslauthd -s n --description 'Use threads processes for responding to authentication queries.'
complete -c saslauthd -s s --description 'Use size as the table size of the hash table (in kilobytes).'
complete -c saslauthd -s t --description 'Use timeout as the expiration time of the authe… [See Man Page]'
complete -c saslauthd -s T --description 'Honour time-of-day login restrictions.'
complete -c saslauthd -s h --description 'Show usage information.'
complete -c saslauthd -s c --description 'Enable cacheing of authentication credentials.'
complete -c saslauthd -s l --description 'Disable the use of a lock file for controlling … [See Man Page]'
complete -c saslauthd -s r --description 'Combine the realm with the login (with an \'@\' sign in between).'
complete -c saslauthd -s v --description 'Print the version number and available authenti… [See Man Page]'
complete -c saslauthd -s d --description 'Debugging mode.'

