# scsd
# Autogenerated from man page /usr/share/man/man8/scsd.8
# using Darwin man parser
complete -c scsd -s l --description 'Get the listening sockets from launchd.'
complete -c scsd -s p --description 'Port to listen on, cannot be used with -l \\" En… [See Man Page]'

