# servermgrd
# Autogenerated from man page /usr/share/man/man8/servermgrd.8
# using Darwin man parser
complete -c servermgrd -s d --description 'Do not move to background and print log strings… [See Man Page]'
complete -c servermgrd -s h --description 'Print usage summary and exit.  Pp.'
complete -c servermgrd -s i --description 'perform doIdle every interval seconds.'
complete -c servermgrd -s p --description 'Use the specified port for cleartext communicat… [See Man Page]'
complete -c servermgrd -s S --description 'Use the specified port for encrypted (SSL) comm… [See Man Page]'
complete -c servermgrd -s v --description 'Print build version and exit.  Pp.'
complete -c servermgrd -s x --description 'Do not move to background.'

