# serveradmin
# Autogenerated from man page /usr/share/man/man8/serveradmin.8
# using Darwin man parser
complete -c serveradmin -s d --description '--debug Print command to the terminal.  Pp.'
complete -c serveradmin -s h --description '--help Print usage summary and exit.  Pp.'
complete -c serveradmin -s v --description '--version Print build version and exit.  Pp.'
complete -c serveradmin -s x --description '--xml Generate output as XML instead of key-value pairs.'

