# sha
# Autogenerated from man page /usr/share/man/man1/sha.1ssl
# using Type1
complete -c sha -s c --description 'print out the digest in two digit groups separa… [See Man Page]'
complete -c sha -s d --description 'print out \\s-1BIO\\s0 debugging information.'
complete -c sha -o hex --description 'digest is to be output as a hex dump.'
complete -c sha -o binary --description 'output the digest or signature in binary form.'
complete -c sha -o out --description 'filename to output to, or standard output by default.'
complete -c sha -o sign --description 'digitally sign the digest using the private key… [See Man Page]'
complete -c sha -o passin --description 'the private key password source.'
complete -c sha -o verify --description 'verify the signature using the the public key i… [See Man Page]'
complete -c sha -o prverify --description 'verify the signature using the  the private key… [See Man Page]'
complete -c sha -o signature --description 'the actual signature to verify.'
complete -c sha -o hmac --description 'create a hashed \\s-1MAC\\s0 using \\*(L"key\\*(R".'
complete -c sha -o rand --description 'a file or files containing random data used to … [See Man Page]'

