# smyrna
# Autogenerated from man page /usr/local/share/man/man1/smyrna.1
# using Deroffing man parser
complete -c smyrna -s v --description 'Verbose mode.'
complete -c smyrna -s '?' --description 'Print usage information.'

