# snmpc
# Autogenerated from man page /usr/local/share/man/man1/snmpc.1
# using Deroffing man parser
complete -c snmpc -l help: --description 'Prints help info.'
complete -c snmpc -l version: --description 'Prints application and mib format version.'
complete -c snmpc -l verbosity --description 'Print debug info.'
complete -c snmpc -l warnings -l W: --description 'Print warning messages.'
complete -c snmpc -l wae -l Werror: --description 'Warnings as errors.'
complete -c snmpc -l o --description 'The directory where the compiler should place the output files.'
complete -c snmpc -l i --description 'Specifies the path to search for imported (compiled) MIB files.'
complete -c snmpc -l il --description 'This option (include_lib), specifies a list of … [See Man Page]'
complete -c snmpc -l sgc: --description 'This option (skip group check), if present, dis… [See Man Page]'
complete -c snmpc -l dep: --description 'Keep deprecated definition(s).'
complete -c snmpc -l desc: --description 'The DESCRIPTION field will be included.'
complete -c snmpc -l ref: --description 'The REFERENCE field will be included.'
complete -c snmpc -l imp: --description 'The IMPORTS field will be included.'
complete -c snmpc -l mi: --description 'The MODULE-IDENTITY field will be included.'
complete -c snmpc -l mc: --description 'The MODULE-COMPLIANCE field will be included.'
complete -c snmpc -l ac: --description 'The AGENT-CAPABILITIES field will be included.'
complete -c snmpc -l mod --description 'The module which implements all the instrumentation functions.'
complete -c snmpc -l nd: --description 'The default instrumentation functions will not … [See Man Page]'
complete -c snmpc -l rrnac: --description 'This option, if present, specifies that the row… [See Man Page]'

