# softwareupdate
# Autogenerated from man page /usr/share/man/man8/softwareupdate.8
# using Darwin man parser
complete -c softwareupdate -s l --description 'List all available updates.'
complete -c softwareupdate -s d --description '.'
complete -c softwareupdate -s i --description 'Each update specified by args is downloaded and… [See Man Page]'
complete -c softwareupdate -l ignore --description 'Manages the per-machine list of ignored updates.'
complete -c softwareupdate -l reset-ignored --description 'Clears the list of all ignored updates.'
complete -c softwareupdate -l schedule --description 'Manages the per-machine scheduler preferences.'
complete -c softwareupdate -s h --description 'Print command usage.'

