# sqlite3
# Autogenerated from man page /usr/share/man/man1/sqlite3.1
# using Deroffing man parser
complete -c sqlite3 -o initfile --description 'Read and execute commands from  file , which ca… [See Man Page]'
complete -c sqlite3 -o echo --description 'Print commands before execution.'
complete -c sqlite3 -o '[no]header' --description 'Turn headers on or off.'
complete -c sqlite3 -o column --description 'Query results will be displayed in a table like… [See Man Page]'
complete -c sqlite3 -o html --description 'Query results will be output as simple HTML tables.'
complete -c sqlite3 -o line --description 'Query results will be displayed with one value … [See Man Page]'
complete -c sqlite3 -o list --description 'Query results will be displayed with the separa… [See Man Page]'
complete -c sqlite3 -o separator --description 'Set output field separator.   Default is \'|\'.'
complete -c sqlite3 -o nullvalue --description 'Set string used to represent NULL values.'
complete -c sqlite3 -o version --description 'Show SQLite version.'
complete -c sqlite3 -o init --description 'Read and execute commands from file , which can… [See Man Page]'
complete -c sqlite3 -o help --description 'Show help on options and exit.'

