# srptool
# Autogenerated from man page /usr/local/share/man/man1/srptool.1
# using Type1
complete -c srptool -s d -l debug --description 'Enable debugging.'
complete -c srptool -s i -l index --description 'specify the index of the group parameters in tpasswd.'
complete -c srptool -s u -l username --description 'specify a username. sp.'
complete -c srptool -s p -l passwd --description 'specify a password file. sp.'
complete -c srptool -s s -l salt --description 'specify salt size.'
complete -c srptool -l verify --description 'just verify the password.'
complete -c srptool -s v -l passwd-conf --description 'specify a password conf file.'
complete -c srptool -l create-conf --description 'Generate a password configuration file.'
complete -c srptool -s h -l help --description 'Display usage information and exit.'
complete -c srptool -s '!' -l more-help --description 'Pass the extended usage information through a pager.'

