# start_erl
# Autogenerated from man page /usr/local/share/man/man1/start_erl.1
# using Deroffing man parser
complete -c start_erl -o reldir --description 'Mandatory if the environment variable RELDIR is… [See Man Page]'
complete -c start_erl -o rootdir --description 'Mandatory if -reldir is not given and there is … [See Man Page]'
complete -c start_erl -o data --description 'Optional, specifies another data file than start_erl.'
complete -c start_erl -o bootflags --description 'Optional, specifies a file name relative to act… [See Man Page]'

