# sv
# Autogenerated from man page /usr/local/share/man/man8/sv.8
# using Deroffing man parser
complete -c sv -s v --description 'If the  command is up, down, term, once, cont, … [See Man Page]'
complete -c sv -s w --description 'Override the default timeout of 7 seconds with sec seconds.'

