# svlogd
# Autogenerated from man page /usr/local/share/man/man8/svlogd.8
# using Deroffing man parser
complete -c svlogd -s t --description 'timestamp.'
complete -c svlogd -o tt --description 'timestamp.'
complete -c svlogd -o ttt --description 'timestamp.'
complete -c svlogd -s r --description 'replace.   c must be a single character.'
complete -c svlogd -s R --description 'replace charset.'
complete -c svlogd -s l --description 'line length.'
complete -c svlogd -s b --description 'buffer size.'
complete -c svlogd -s v --description 'verbose.  Print verbose messages to standard error.'

