# symcryptrun
# Autogenerated from man page /usr/local/MacGPG2/share/man/man1/symcryptrun.1
# using Deroffing man parser
complete -c symcryptrun -s v --description '.'
complete -c symcryptrun -l verbose --description 'Output additional information while running.'
complete -c symcryptrun -s q --description '.'
complete -c symcryptrun -l quiet --description 'Try to be as quiet as possible.'
complete -c symcryptrun -l homedir --description 'Set the name of the home directory to dir.'
complete -c symcryptrun -l log-file --description 'Append all logging output to file.'

