# sysctl
# Autogenerated from man page /usr/share/man/man8/sysctl.8.gz
# using Darwin man parser
complete -c sysctl -s A --description 'List all MIB variables including opaque variabl… [See Man Page]'
complete -c sysctl -s a --description 'List all the currently available non-opaque values.'
complete -c sysctl -s b --description 'Force the value of the variable(s) to be output… [See Man Page]'
complete -c sysctl -s n --description 'Show only variable values, not their names.'
complete -c sysctl -s w --description 'Used to set values.'
complete -c sysctl -s X --description 'Same as A, but prints a hex dump of the entire … [See Man Page]'

