# SystemStarter
# Autogenerated from man page /usr/share/man/man8/SystemStarter.8.gz
# using Darwin man parser
complete -c SystemStarter -s g --description '(ignored).'
complete -c SystemStarter -s v --description 'verbose (text mode) startup.'
complete -c SystemStarter -s x --description '(ignored).'
complete -c SystemStarter -s r --description '(ignored).'
complete -c SystemStarter -s d --description 'print debugging output.'
complete -c SystemStarter -s D --description 'print debugging output and dependencies.'
complete -c SystemStarter -s q --description 'be quiet (disable debugging output).'
complete -c SystemStarter -s n --description 'don\'t actually perform action on items (no-run … [See Man Page]'

