# talagent
# Autogenerated from man page /usr/share/man/man8/talagent.8
# using Darwin man parser
complete -c talagent -o dump --description 'Outputs the persistent state of an application … [See Man Page]'
complete -c talagent -o launch --description 'Launches an application stopped, as they are la… [See Man Page]'
complete -c talagent -o memory_pressure --description 'Simulates memory pressure, which may cause apps… [See Man Page]'

