# tcpclient
# Autogenerated from man page /usr/local/share/man/man1/tcpclient.1
# using Deroffing man parser
complete -c tcpclient -o ilocalip --description 'Use  localip as the IP address for the local si… [See Man Page]'
complete -c tcpclient -o plocalport --description 'Use  localport as the port number for the local… [See Man Page]'
complete -c tcpclient -o Iinterface --description 'Use  interface as the local network interface.'
complete -c tcpclient -o Ttimeoutconn --description 'Give up on the connection attempt after  timeoutconn seconds.'
complete -c tcpclient -s d --description '(Default.'
complete -c tcpclient -s D --description 'Never delay sending data; enable TCP_NODELAY.'
complete -c tcpclient -s q --description 'Quiet.  Do not print any messages.'
complete -c tcpclient -s Q --description '(Default. ) Print error messages.'
complete -c tcpclient -s v --description 'Verbose.  Print all available messages.'
complete -c tcpclient -s h --description '(Default. ) Look up the remote host name for TCPREMOTEHOST .'
complete -c tcpclient -s H --description 'Do not look up the remote host name; unset TCPREMOTEHOST .'
complete -c tcpclient -o llocalname --description 'Do not look up the local host name; use localna… [See Man Page]'
complete -c tcpclient -s r --description '(Default.'
complete -c tcpclient -s R --description 'Do not attempt to obtain TCPREMOTEINFO from the remote host.'
complete -c tcpclient -o ttimeoutinfo --description 'Give up on the  TCPREMOTEINFO connection attemp… [See Man Page]'
complete -c tcpclient -s 4 --description 'Fall back to IPv4 sockets.'
complete -c tcpclient -s 6 --description 'Force IPv6 mode in UCSPI environment variables,… [See Man Page]'

