# tcpserver
# Autogenerated from man page /usr/local/share/man/man1/tcpserver.1
# using Type1
complete -c tcpserver -o climit --description 'Do not handle more than  limit simultaneous connections.'
complete -c tcpserver -o 'xrules.cdb' --description 'Follow the rules compiled into  rules. cdb by  tcprules .'
complete -c tcpserver -o Bbanner --description 'Write  banner to the network immediately after … [See Man Page]'
complete -c tcpserver -o ggid --description 'Switch group ID to  gid after preparing to receive connections.'
complete -c tcpserver -o uuid --description 'Switch user ID to   uid after preparing to receive connections.'
complete -c tcpserver -s 1 --description 'After preparing to receive connections, print t… [See Man Page]'
complete -c tcpserver -s 4 --description 'Fall back to IPv4 sockets.'
complete -c tcpserver -s 6 --description 'Force IPv6 mode in UCSPI environment variables,… [See Man Page]'
complete -c tcpserver -o Iinterface --description 'Bind to the network interface  interface ("eth0… [See Man Page]'
complete -c tcpserver -o bbacklog --description 'Allow up to  backlog simultaneous SYN_RECEIVEDs.  Default: 20.'
complete -c tcpserver -s o --description 'Leave IP options alone.'
complete -c tcpserver -s O --description '(Default. ) Kill IP options.'
complete -c tcpserver -s d --description '(Default.'
complete -c tcpserver -s D --description 'Never delay sending data; enable TCP_NODELAY.'
complete -c tcpserver -s q --description 'Quiet.  Do not print any messages.'
complete -c tcpserver -s Q --description '(Default. ) Print error messages.'

