# tificc
# Autogenerated from man page /usr/local/share/man/man1/tificc.1
# using Deroffing man parser
complete -c tificc -s a --description 'Handle channels > 4 as alpha.'
complete -c tificc -s b --description 'Black point compensation.'
complete -c tificc -s c --description 'Precalculates transform.'
complete -c tificc -s e --description 'Embed destination profile.'
complete -c tificc -s g --description 'Marks out-of-gamut colors on softproof.'
complete -c tificc -s h --description 'Show summary of options and examples.'
complete -c tificc -o iprofile --description 'Input profile (defaults to sRGB).'
complete -c tificc -s k --description 'Ink-limiting in % (CMYK only).'
complete -c tificc -o lprofile --description 'Transform by device-link profile.'
complete -c tificc -s m --description 'SoftProof intent.'
complete -c tificc -s n --description 'Ignore embedded profile on input.'
complete -c tificc -s p --description 'Soft proof profile.'
complete -c tificc -s o --description 'p Output profile (defaults to sRGB).'
complete -c tificc -s s --description 'Save embedded profile as <new profile>.'
complete -c tificc -s t --description 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturat… [See Man Page]'
complete -c tificc -s v --description 'Verbose.'
complete -c tificc -s w --description 'Wide output (generates 16 bps tiff).'
complete -c tificc -s i --description 'Input profile (defaults to sRGB).'
complete -c tificc -s l --description 'Transform by device-link profile.'

