# tmutil
# Autogenerated from man page /usr/share/man/man8/tmutil.8
# using Darwin man parser
complete -c tmutil -s a --description 'compare all suppored metadata.'
complete -c tmutil -s @ --description 'compare extended attributes.'
complete -c tmutil -s e --description 'compare ACLs.'
complete -c tmutil -s s --description 'compare sizes.'
complete -c tmutil -s m --description 'compare file modes.'
complete -c tmutil -s u --description 'compare UIDs.'
complete -c tmutil -s g --description 'compare GIDs.'
complete -c tmutil -s t --description 'compare modification times.'
complete -c tmutil -s d --description 'compare file data forks.'
complete -c tmutil -s r --description 'ignore specified root paths and compare descendents instead.'
complete -c tmutil -s D --description 'limit traversal depth to depth levels from the … [See Man Page]'
complete -c tmutil -s E --description 'don\'t take exclusions into account when compari… [See Man Page]'
complete -c tmutil -s I --description 'ignore paths with a path component equal to nam… [See Man Page]'
complete -c tmutil -s v --description 'enable verbose mode (enables reporting of all i… [See Man Page]'
complete -c tmutil -s X --description 'print output in XML property list format El - -… [See Man Page]'

