# tpmtool
# Autogenerated from man page /usr/local/share/man/man1/tpmtool.1
# using Type1
complete -c tpmtool -s d -l debug --description 'Enable debugging.'
complete -c tpmtool -l infile --description 'Input file. sp.'
complete -c tpmtool -l outfile --description 'Output file. sp.'
complete -c tpmtool -l generate-rsa --description 'Generate an RSA private-public key pair.'
complete -c tpmtool -l register --description 'Any generated key will be registered in the TPM.'
complete -c tpmtool -l signing --description 'Any generated key will be a signing key.'
complete -c tpmtool -l legacy --description 'Any generated key will be a legacy key.'
complete -c tpmtool -l user --description 'Any registered key will be a user key.'
complete -c tpmtool -l system --description 'Any registred key will be a system key.'
complete -c tpmtool -l pubkey --description 'Prints the public key of the provided key. sp.'
complete -c tpmtool -l list --description 'Lists all stored keys in the TPM. sp.'
complete -c tpmtool -l delete --description 'Delete the key identified by the given URL (UUID). sp.'
complete -c tpmtool -l sec-param --description 'Specify the security level [low, legacy, normal, high, ultra].'
complete -c tpmtool -l bits --description 'Specify the number of bits for key generate.'
complete -c tpmtool -l inder -l no-inder --description 'Use the DER format for keys.'
complete -c tpmtool -l outder -l no-outder --description 'Use DER format for output keys.'
complete -c tpmtool -s h -l help --description 'Display usage information and exit.'
complete -c tpmtool -s '!' -l more-help --description 'Pass the extended usage information through a pager.'

