# tsplot
# Autogenerated from man page /usr/local/share/man/man1/tsplot.1
# using Deroffing man parser
complete -c tsplot -s c --description '.'
complete -c tsplot -l config --description 'specifies the configuration file to use.  Default is http. en.'
complete -c tsplot -s d --description '.'
complete -c tsplot -l outdir --description 'directory where tsplot saves the images it prod… [See Man Page]'
complete -c tsplot -s v --description '.'
complete -c tsplot -l verbose --description 'makes tsplot very verbose about what it does.  CONFIGURATION.'

