# tsung-recorder
# Autogenerated from man page /usr/local/share/man/man1/tsung-recorder.1
# using Type1
complete -c tsung-recorder -s l --description 'Specifies the log file to use.'
complete -c tsung-recorder -s p --description 'Specifies the plugin used for the recorder.'
complete -c tsung-recorder -s L --description 'Listening port for the recorder.  Default is 8090.'
complete -c tsung-recorder -s I --description 'For the pgsql recorder (or parent proxy): server IP.'
complete -c tsung-recorder -s P --description 'For the pgsql recorder (or parent proxy): server port.'

