# tsung
# Autogenerated from man page /usr/local/share/man/man1/tsung.1
# using Type1
complete -c tsung -s f --description 'specifies the configuration file to use.'
complete -c tsung -s l --description 'Specifies the log directory to use.'
complete -c tsung -s m --description 'Specifies the monitoring log file name to use.'
complete -c tsung -s r --description 'Specifies an alternative to ssh (rsh for ex.'
complete -c tsung -s i --description 'set controller id (default is empty).'
complete -c tsung -s F --description 'Use long names for erlang nodes (FQDN).'
complete -c tsung -s v --description 'Show version.'
complete -c tsung -s 6 --description 'Use IPv6 for tsung internal communications.'

