# varnishtop
# Autogenerated from man page /usr/local/share/man/man1/varnishtop.1
# using Deroffing man parser
complete -c varnishtop -s 1 --description 'Instead of presenting of a continuously updated… [See Man Page]'
complete -c varnishtop -s b --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishtop -s C --description 'Ignore case when matching regular expressions.'
complete -c varnishtop -s c --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishtop -s d --description 'Process old log entries on startup.'
complete -c varnishtop -s f --description 'Sort and group only on the first field of each log entry.'
complete -c varnishtop -s I --description 'Include log entries which match the specified r… [See Man Page]'
complete -c varnishtop -s i --description 'Include log entries with the specified tag.'
complete -c varnishtop -s p --description 'Specifies the number of seconds to measure over… [See Man Page]'
complete -c varnishtop -s n --description 'Specifies the name of the varnishd instance to get logs from.'
complete -c varnishtop -s r --description 'Read log entries from file instead of shared memory.'
complete -c varnishtop -s V --description 'Display the version number and exit.'
complete -c varnishtop -s X --description 'Exclude log entries which match the specified r… [See Man Page]'
complete -c varnishtop -s x --description 'Exclude log entries with the specified tag.'

