# varnishsizes
# Autogenerated from man page /usr/local/share/man/man1/varnishsizes.1
# using Deroffing man parser
complete -c varnishsizes -s b --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishsizes -s C --description 'Ignore case when matching regular expressions.'
complete -c varnishsizes -s c --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishsizes -s d --description 'Process old log entries on startup.'
complete -c varnishsizes -s I --description 'Include log entries which match the specified r… [See Man Page]'
complete -c varnishsizes -s i --description 'Include log entries with the specified tag.'
complete -c varnishsizes -s m -s m --description 'options are AND-ed together. UNINDENT NDENT 0. 0.'
complete -c varnishsizes -s n --description 'Specifies the name of the varnishd instance to get logs from.'
complete -c varnishsizes -s r --description 'Read log entries from file instead of shared memory.'
complete -c varnishsizes -s V --description 'Display the version number and exit.'
complete -c varnishsizes -s w --description 'Wait at least delay seconds between each update.'
complete -c varnishsizes -s X --description 'Exclude log entries which match the specified r… [See Man Page]'
complete -c varnishsizes -s x --description 'Exclude log entries with the specified tag.'

