# varnishncsa
# Autogenerated from man page /usr/local/share/man/man1/varnishncsa.1
# using Deroffing man parser
complete -c varnishncsa -s a --description 'When writing to a file, append to it rather than overwrite it.'
complete -c varnishncsa -s C --description 'Ignore case when matching regular expressions.'
complete -c varnishncsa -s D --description 'Daemonize.'
complete -c varnishncsa -s d --description 'Process old log entries on startup.'
complete -c varnishncsa -s f --description 'Prefer the X-Forwarded-For HTTP header over client.'
complete -c varnishncsa -s F --description 'Specify the log format used.'
complete -c varnishncsa -s m --description '-m options are AND-ed together. UNINDENT NDENT 0. 0.'
complete -c varnishncsa -s n --description 'Specifies the name of the varnishd instance to get logs from.'
complete -c varnishncsa -s P --description 'Write the process\\(aqs PID to the specified file.'
complete -c varnishncsa -s r --description 'Read log entries from file instead of shared memory.'
complete -c varnishncsa -s V --description 'Display the version number and exit.'
complete -c varnishncsa -s w --description 'Write log entries to file instead of displaying them.'
complete -c varnishncsa -s X --description 'Exclude log entries which match the specified r… [See Man Page]'
complete -c varnishncsa -s x --description 'Exclude log entries with the specified tag.'

