# varnishreplay
# Autogenerated from man page /usr/local/share/man/man1/varnishreplay.1
# using Deroffing man parser
complete -c varnishreplay -s a --description 'Send the traffic over tcp to this server, speci… [See Man Page]'
complete -c varnishreplay -s D --description 'Turn on debugging mode.'
complete -c varnishreplay -s r --description 'Parse logs from this file.   This option is mandatory.'

