# varnishadm
# Autogenerated from man page /usr/local/share/man/man1/varnishadm.1
# using Deroffing man parser
complete -c varnishadm -s t --description 'Wait no longer than this many seconds for an op… [See Man Page]'
complete -c varnishadm -s S --description 'Specify the authentication secret file.'
complete -c varnishadm -s T --description 'Connect to the management interface at the spec… [See Man Page]'
complete -c varnishadm -s n --description 'Connect to the instance of varnishd with this name.'

