# varnishhist
# Autogenerated from man page /usr/local/share/man/man1/varnishhist.1
# using Deroffing man parser
complete -c varnishhist -s b --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishhist -s C --description 'Ignore case when matching regular expressions.'
complete -c varnishhist -s c --description 'Include log entries which result from communica… [See Man Page]'
complete -c varnishhist -s d --description 'Process old log entries on startup.'
complete -c varnishhist -s I --description 'Include log entries which match the specified r… [See Man Page]'
complete -c varnishhist -s i --description 'Include log entries with the specified tag.'
complete -c varnishhist -s m --description '-m options are AND-ed together. UNINDENT NDENT 0. 0.'
complete -c varnishhist -s n --description 'Specifies the name of the varnishd instance to get logs from.'
complete -c varnishhist -s r --description 'Read log entries from file instead of shared memory.'
complete -c varnishhist -s V --description 'Display the version number and exit.'
complete -c varnishhist -s w --description 'Wait at least delay seconds between each update.'
complete -c varnishhist -s X --description 'Exclude log entries which match the specified r… [See Man Page]'
complete -c varnishhist -s x --description 'Exclude log entries with the specified tag.'

