# varnishstat
# Autogenerated from man page /usr/local/share/man/man1/varnishstat.1
# using Deroffing man parser
complete -c varnishstat -s 1 --description 'Instead of presenting of a continuously updated… [See Man Page]'
complete -c varnishstat -s f --description 'A comma separated list of the fields to display.'
complete -c varnishstat -s l --description 'Lists the available fields to use with the -f option.'
complete -c varnishstat -s n --description 'Specifies the name of the varnishd instance to get logs from.'
complete -c varnishstat -s V --description 'Display the version number and exit.'
complete -c varnishstat -s w --description 'Wait delay seconds between updates.   The default is 1.'
complete -c varnishstat -s x --description 'Displays the result as XML.'
complete -c varnishstat -s j --description 'Displays the result as JSON.'

