# varnishtest
# Autogenerated from man page /usr/local/share/man/man1/varnishtest.1
# using Deroffing man parser
complete -c varnishtest -s i --description 'Find varnishd in build tree.'
complete -c varnishtest -s j --description 'Run this many tests in parallel.'
complete -c varnishtest -s k --description 'Continue on test failure.'
complete -c varnishtest -s l --description 'Leave /tmp/vtc. * if test fails.'
complete -c varnishtest -s L --description 'Always leave /tmp/vtc. *.'
complete -c varnishtest -s n --description 'Run tests this many times.'
complete -c varnishtest -s q --description 'Quiet mode: report only failures.'
complete -c varnishtest -s t --description 'Time tests out after this long.'
complete -c varnishtest -s v --description 'Verbose mode: always report test log.'
complete -c varnishtest -s D --description '.'
complete -c varnishtest -s h --description 'Show help file             File to use as a script.'

