# wait_on
# Autogenerated from man page /usr/local/share/man/man1/wait_on.1.gz
# using Darwin man parser
complete -c wait_on -s c --description 'Print version string, copyright notice and exit.'
complete -c wait_on -s h --description 'Write information about changes to the standard… [See Man Page]'
complete -c wait_on -s i --description 'Exit with an exit value that indicates to which… [See Man Page]'
complete -c wait_on -s v --description 'Print version string, copyright notice and exit.'
complete -c wait_on -s w --description 'Only exit when something is written (i. e.'
complete -c wait_on -s t --description 'Wait for timeout seconds for an event to occur … [See Man Page]'

