# watchgnupg
# Autogenerated from man page /usr/local/MacGPG2/share/man/man1/watchgnupg.1
# using Deroffing man parser
complete -c watchgnupg -l force --description 'Delete an already existing socket file.'
complete -c watchgnupg -l tcp --description 'Instead of reading from a local socket, listen … [See Man Page]'
complete -c watchgnupg -l verbose --description 'Enable extra informational output.'
complete -c watchgnupg -l version --description 'Print version of the program and exit.'
complete -c watchgnupg -l help --description 'Display a brief help page and exit.'

