# watch
# Autogenerated from man page /usr/local/share/man/man1/watch.1
# using Deroffing man parser
complete -c watch -s n --description 'or.'
complete -c watch -l interval --description 'to specify a different interval.'
complete -c watch -s d --description 'or.'
complete -c watch -l differences --description 'flag will highlight the differences between successive updates.'
complete -c watch -l cumulative --description 'option makes highlighting "sticky", presenting … [See Man Page]'
complete -c watch -s t --description 'or.'
complete -c watch -l no-title --description 'option turns off the header showing the interva… [See Man Page]'

