# xcmsdb
# Autogenerated from man page /usr/X11/share/man/man1/xcmsdb.1.gz
# using Deroffing man parser
complete -c xcmsdb -o format --description 'Specifies the property format (32, 16, or 8 bit… [See Man Page]'

