# xcrun
# Autogenerated from man page /usr/share/man/man1/xcrun.1
# using Darwin man parser
complete -c xcrun -o verbose --description 'Display information about how the redirected pa… [See Man Page]'
complete -c xcrun -o no-cache --description 'Don\'t consult the cache when looking up values.'
complete -c xcrun -o kill-cache --description 'Removes the cache.   Causes all values to be re-cached.'
complete -c xcrun -o sdk --description 'Specifies which SDK to use.'
complete -c xcrun -o log --description 'Print the full command line that is invoked.'
complete -c xcrun -o find --description 'Print the full path to the tool.'

