# xinput
# Autogenerated from man page /usr/X11/share/man/man1/xinput.1.gz
# using Deroffing man parser
complete -c xinput -l 'long]' --description 'If no argument is given list all the input devices.'
complete -c xinput -l test_xi2 --description 'Register for a number of XI2 events and display them.'

