# xlsatoms
# Autogenerated from man page /usr/X11/share/man/man1/xlsatoms.1.gz
# using Deroffing man parser
complete -c xlsatoms -o name --description 'This option specifies the name of an atom to list.'

