# xman
# Autogenerated from man page /usr/X11/share/man/man1/xman.1.gz
# using Deroffing man parser
complete -c xman -o pagesize --description 'Sets the size and location of all the Manual Pages.'
complete -c xman -l '-------	------------' --description 'man1	(1) User Commands man2	(2) System Calls ma… [See Man Page]'

