# xmkmf
# Autogenerated from man page /usr/local/share/man/man1/xmkmf.1
# using Deroffing man parser
complete -c xmkmf -s a --description 'option, xmkmf builds the Makefile in the curren… [See Man Page]'

