# xrdb
# Autogenerated from man page /usr/X11/share/man/man1/xrdb.1.gz
# using Deroffing man parser
complete -c xrdb -o 'merge)' --description 'or to the resource file (when used with -edit) … [See Man Page]'
complete -c xrdb -o Idirectory --description 'This option is passed through to the preprocess… [See Man Page]'

