# ypinit
# Autogenerated from man page /usr/share/man/man8/ypinit.8.gz
# using Darwin man parser
complete -c ypinit -s m --description 'Setup a master YP server.'
complete -c ypinit -s s --description 'Setup a slave YP server.'
complete -c ypinit -s u --description 'Update the ypserver map on a YP master server.'

