# yppush
# Autogenerated from man page /usr/share/man/man8/yppush.8.gz
# using Darwin man parser
complete -c yppush -s d --description 'Don\'t use default domain, use the specified domain.'
complete -c yppush -s h --description 'Distribute map only to one host and not to the … [See Man Page]'
complete -c yppush -s v --description 'Verbose.  Announce what the program is doing.'

