# ypserv
# Autogenerated from man page /usr/share/man/man8/ypserv.8.gz
# using Darwin man parser
complete -c ypserv -s 1 --description 'Allow ypserv to answer old YP version 1 requests.'
complete -c ypserv -s a --description 'Don\'t use /var/yp/securenet.'
complete -c ypserv -s d --description 'Use Internet Domain Name System.  If a query to map hosts.'
complete -c ypserv -s x --description 'Terminate the server after processing aclfile o… [See Man Page]'

