# ypxfr
# Autogenerated from man page /usr/share/man/man8/ypxfr.8.gz
# using Darwin man parser
complete -c ypxfr -s b --description 'Preserve the entry in the database informing a … [See Man Page]'
complete -c ypxfr -s c --description 'Don\'t send a "Clear current map" to local ypserv process.'
complete -c ypxfr -s f --description 'Force map transfer, even if version of master i… [See Man Page]'
complete -c ypxfr -s d --description 'Don\'t use default domain, use the specifiyed domain.'
complete -c ypxfr -s h --description 'Get map from host insteed of the maps master host.'
complete -c ypxfr -s s --description 'Specify a source domain other than the target domain.'
complete -c ypxfr -s C --description 'This option is only used by ypserv.'

